---
title: "Air temp analysis"
author: "Abby Lewis"
date: "2023-05-22"
output: html_document
---

This file analyzes the effect of variation in air temperature on hypolimnetic temperature and DO.

Table of contents: 
- Step 1: Load packages and data 
- Step 2: Generate temp anomaly summary fig 
- Step 3: Analyze the effect of monthly air temperature on hypolimnetic DO, VHOD, and temp dynamics


Step 1: Load packages and data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
#library(mosaic)
#library(ggallin)
#library(ppcor)
#library(multcompView)
#library(ggpubr)
#library(viridis)
#library(MASS)
#library(see)
source("lmer_functions.R")

#Load saved data
with_temp = read.csv("../Compiled data/All_data_annual AF.csv")
lat_long <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/1530/1/fadd3eaa25b5fdd1fc4efba70e660579")

# Make a directory for Figures if there isn't one
if (!dir.exists("../Figures")){dir.create("../Figs")}
```

```{r}
sp <- yday(c("2022-03-01", "2022-05-31"))
su <- yday(c("2022-07-01", "2022-08-31"))
memory <- all %>% 
  filter(var %in% c("Summer epi. temperature",
                    "Summer epi. DO sat",
                    "Summer hypo. temperature",
                    "Summer VHOD",
                    "Summer hypo. DO")) %>%
  mutate(var = factor(var, levels = c("Summer epi. temperature",
                                      "Summer epi. DO sat",
                                      "Summer hypo. temperature",
                                      "Summer VHOD",
                                      "Summer hypo. DO"),
                      labels = c("Summer epi. temperature",
                                 "Summer epi. DO sat",
                                 "Summer bottom-water\ntemperature",
                                 "Summer VHOD",
                                 "Summer bottom-water\ndissolved oxygen")),
         season = ifelse(doy >= sp[1] & doy <= sp[2], "spring", 
                         ifelse(doy >= su[1] & doy <= su[2], "summer", NA))) %>%
  group_by(var) %>%
  mutate(p = wilcox.test(monthly_correlation)$p.value) %>%
  filter(!is.na(season)) %>%
  group_by(LakeID, var, season, p) %>%
  summarize(max = max(abs(monthly_correlation))) %>%
  pivot_wider(names_from = season, values_from = max) %>%
  mutate(M = (summer - spring)) 

summer_avgs = read.csv("../Compiled data/summer_averages_wi.csv")%>%
  group_by(LakeID) %>%
  summarize(buoyancy_freq = median(buoyancy_freq, na.rm = T))

mean_temps <- with_temp %>%
  mutate(spring_temp = (temp_mar + temp_apr + temp_may)/3,
         summer_temp = (temp_july + temp_aug)/2) %>%
  group_by(LakeID) %>%
  summarize(spring_temp = mean(spring_temp, na.rm = T),
            summer_temp = mean(summer_temp, na.rm = T),
            annual_temp = mean(mean_temp, na.rm = T),
            tp = mean(TP_ugL_EPI, na.rm = T))

mem_plot <- memory %>%
  filter(var %in% c("Summer bottom-water\ntemperature",
                    "Summer bottom-water\ndissolved oxygen")) %>%
  left_join(summer_avgs) %>%
  left_join(lat_long) %>%
  mutate(SA_class = ifelse(SurfaceArea_ha > 100, "> 100 ha", "≤ 100 ha")) %>%
  filter(!is.na(SurfaceArea_ha)) %>%
  ggplot(aes(x = buoyancy_freq, y = M))+
  geom_hline(yintercept = 0)+
  geom_point(aes(color = SA_class, shape = SA_class))+
  geom_smooth(method = "lm", aes(color = SA_class))+
  ylab("Relative correlation with\nsummer vs. spring air temp")+
  #stat_cor(label.y = 0.7) +
  theme_bw() +
  xlab("Maximum buoyancy frequency (1/s)")+
  scale_color_manual(name = "Lake size", values = c("#202C39", "#65A47D"))+
  scale_shape_discrete(name = "Lake size")+
  facet_wrap(~var)+
  ylab("\n\n")+
  geom_text(x = 0, y = 0.65, label = "More correlated\nwith summer", 
           hjust = 1, lineheight = .9, size = 3, 
           data = data.frame(var = factor("Summer bottom-water\ntemperature",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  geom_text(x = 0, y = -0.65, label = "More correlated\nwith spring", 
           hjust = 1, lineheight = .9, size = 3, 
           data = data.frame(var = factor("Summer bottom-water\ntemperature",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  coord_cartesian(ylim = c(-0.65,0.65), clip = "off")

mem_plot
```

```{r}
mem_lm <- memory %>%
  left_join(summer_avgs) %>%
  left_join(mean_temps) %>%
  left_join(lat_long) %>%
  mutate(log_SA = log(SurfaceArea_ha),
         log_max_depth = log(MaximumDepth_m),
         log_tp = log(tp),
         temp_dif = summer_temp-spring_temp) %>%
  pivot_wider(names_from = var, values_from = M) %>%
  rename(epi_temp = `Summer epi. temperature`,
         hypo_temp = `Summer bottom-water\ntemperature`,
         hypo_do = `Summer bottom-water\ndissolved oxygen`,
         vhod = `Summer VHOD`,
         epi_do_sat = `Summer epi. DO sat`)

responses <- c("epi_temp")
potential_drivers <- c("log_SA", "log_max_depth", "buoyancy_freq")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(epi_temp ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
#Intercept only model is best

responses <- c("epi_do_sat")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(epi_do_sat ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
#intercept only model is equivalent

responses <- c("hypo_temp")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(hypo_temp ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
mod_lm_temp <- lm(hypo_temp~log_SA+buoyancy_freq+log_max_depth+log_max_depth:log_SA, 
             data = mem_lm_df) 
temp <- plot_effects_lm(mod_lm_temp,"Relative correlation\nsummer hypo. temp") 

responses <- c("hypo_do")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(hypo_do ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
mod_lm_do <- lm(hypo_do~log_SA+buoyancy_freq, data = mem_lm_df) 
do <- plot_effects_lm(mod_lm_do,"Relative correlation\nsummer hypo. DO") 

responses <- c("vhod")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(vhod ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
#Intercept only model is best

#Plot temp and DO together
#Temp first
effects_temp = data.frame(summary(mod_lm_temp)$coefficients)%>%
  rename(std_error = Std..Error)
effects_temp$Var = row.names(effects_temp)
confs_temp = data.frame(confint(mod_lm_temp))
confs_temp$Var = row.names(confs_temp)
effects2_temp = effects_temp%>%
  left_join(confs_temp)%>%
  rename(xmin = X2.5..,
         xmax = X97.5..)
#DO
effects_do = data.frame(summary(mod_lm_do)$coefficients)%>%
  rename(std_error = Std..Error)
effects_do$Var = row.names(effects_do)
confs_do = data.frame(confint(mod_lm_do))
confs_do$Var = row.names(confs_do)
effects2_do = effects_do%>%
  left_join(confs_do)%>%
  rename(xmin = X2.5..,
         xmax = X97.5..)
#Combine
effects2 <- effects2_temp %>%
  mutate(name = "hypo_temp")%>%
  full_join(effects2_do %>% mutate(name = "hypo_do"))
comb <- effects2%>%
  filter(!Var=="(Intercept)")%>%
  mutate(Var = renamer(Var),
         Var = factor(Var, levels = Var[order(abs(Estimate[name == "hypo_temp"]))]))%>%
  mutate(name = factor(name, 
                       levels = c("hypo_temp",
                                  "hypo_do"),
                       labels = c("Summer bottom-water\ntemperature",
                                  "Summer bottom-water\ndissolved oxygen"))) %>%
  ggplot(aes(y = Var, x=Estimate))+
  geom_vline(xintercept = 0)+
  geom_point()+
  geom_errorbar(aes(xmin=xmin, xmax = xmax),width=0.1)+
  theme_bw()+
  xlab("Parameter estimate")+
  geom_text(x = -0.5, y = -0.8, label = "More correlated\nwith spring", 
           hjust = 0, lineheight = .9, size = 3, 
           data = data.frame(name = factor("Summer bottom-water\ntemperature",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  geom_text(x = 0.15, y = -0.8, label = "More correlated\nwith summer", 
           hjust = 1, lineheight = .9, size = 3, 
           data = data.frame(name = factor("Summer bottom-water\ndissolved oxygen",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  theme(axis.title.y = element_blank(),
        plot.margin = unit(c(5.5, 5.5, 10, 5.5), "pt"))+
  facet_wrap(~name)+
  coord_cartesian(ylim = c(1, 4), clip = F)

jpeg("../Figures/Memory drivers.jpg", res = 300, width = 5, height = 5.5, units = "in")
ggarrange(comb +
            ggtitle("Relative correlation with summer vs. spring air temp") +
            theme(plot.title = element_text(size = 11)),
          mem_plot + 
            guides(shape = guide_legend(override.aes = list(size = 3)))+
            theme(legend.position = "bottom",
                  legend.margin=margin(c(0,0,0,0))),
          nrow = 2, 
          align = "v", heights = c(1,1.4), labels = "auto", label.x = .1)+
  theme(plot.margin = margin(0.1,0.1,0.1,-1, "cm"))
dev.off()

comb
```