---
title: "Untitled"
author: "Abby Lewis"
date: "2023-10-10"
output: html_document
---

Step 1: Load packages and data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(trend) #switched from openair 7 Nov 2023

# Make a directory for Figures if there isn't one
if (!dir.exists("../Figures")){dir.create("../Figures")}
lat_long <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/1530/1/fadd3eaa25b5fdd1fc4efba70e660579")
```

Step 2: Calculate water temperature trends

```{r}
all_data <- read.csv("../Compiled data/All_data_annual.csv")
#Function
sen_slope_custom <- function(df,var){
  output = df%>%
    group_by(LakeID)%>%
    dplyr::summarize(n = n(),
              trend = NA,
              sig = NA,
              min_year = NA,
              max_year = NA)
  for(lake in unique(df$LakeID)){
    filt = df %>%
      filter(LakeID==lake) %>%
      mutate(date = as.POSIXct(paste0(Year,"-01-01"))) %>%
      ungroup()%>%
      dplyr::select(-Year)
    if(length(unique(year(filt$date)))>=10){#Only calculate a trend if there are 10 years of data
      sen = trend::sens.slope(filt[[var]])
      output$trend[output$LakeID==lake]<-sen$estimates[1]
      output$sig[output$LakeID==lake]<-sen$p.value[1]
      output$min_year[output$LakeID==lake]<-min(year(filt$date))
      output$max_year[output$LakeID==lake]<-max(year(filt$date))
      output$var <- var
    }
  }
  return(output)
}

summer_mean_sen <- sen_slope_custom(all_data %>% filter(!is.na(Temp_C_HYPO)), "Temp_C_HYPO")
summer_epi_sen <- sen_slope_custom(all_data %>% filter(!is.na(Temp_C_EPI)), "Temp_C_EPI")
summer_do_sen <- sen_slope_custom(all_data %>% filter(!is.na(DO_mgL_HYPO), DO_mgL_HYPO > 1), "DO_mgL_HYPO")

write.csv(summer_epi_sen, "../Compiled data/summer_epi_temp_trends.csv", row.names = F)
write.csv(summer_mean_sen, "../Compiled data/summer_hypo_temp_mean_trends.csv", row.names = F)
```

Step 3: Calculate daily air temperature trends

```{r}
#Load data
climate_era5 = read.csv("../Compiled data/historical_temp_output_era5_daily.csv")

climate_era5_roll <- climate_era5 %>%
  mutate(doy = yday(Date),
         Year = year(Date)) %>%
  group_by(LakeID) %>%
  arrange(Date) %>%
  mutate(Temp_C = zoo::rollmean(Temp_C, 30, align = "right", fill = NA)) %>%
  filter(doy < yday(as.Date("2022-08-31")),
         !is.na(Temp_C))

#Calculate trends
climate_era5_trends <- sen_slope_doys(climate_era5_roll, 
                                        "Temp_C",
                                        doys = 1:max(climate_era5_roll$doy))

#Save output
write.csv(climate_era5_trends, 
          "../Compiled data/climate_era5_roll_Temp_C_daily.csv", 
              row.names = F)
```

