---
title: "Air temp trends"
author: "Abby Lewis"
date: "2023-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(trend)
library(ggh4x)
library(ggpubr)
library(randomForest)

# Make a directory for Figures if there isn't one
if (!dir.exists("../Figures")){dir.create("../Figures")}

# Load data
lat_long = read.csv("https://pasta-s.lternet.edu/package/data/eml/edi/1029/9/fadd3eaa25b5fdd1fc4efba70e660579")
trends <- read.csv('../Compiled data/climate_era5_roll_met_daily.csv')
max_cor_dates <- read.csv("../Compiled data/strongest_correlation_dates_all_met_3m.csv")
max_cor_dates_hypo_surf_bot <- read.csv("../Compiled data/strongest_correlation_dates_hypo_surf_bot.csv")
mem <- read_csv("../Compiled data/memory_3m.csv") %>%
  mutate(var = recode(var, 
                      "Summer bottom-water\ntemperature" = "summer_bot_mean",
                      "Summer bottom-water\ndissolved oxygen" = "summer_bot_do",
                      "Summer epi. temperature" = "summer_surf_mean"))
summer_bot_mean <- read.csv("../Compiled data/summer_bot_temp_mean_trends_3m.csv") %>%
  rename(summer_bot_mean = trend) %>%
  dplyr::select(summer_bot_mean, LakeID)
summer_surf_mean <- read.csv("../Compiled data/summer_surf_temp_trends_3m.csv") %>%
  rename(summer_surf_mean = trend) %>%
  dplyr::select(summer_surf_mean, LakeID)
summer_bot_do <- read.csv("../Compiled data/summer_bot_DO_trends_3m.csv") %>%
  rename(summer_bot_do = trend) %>%
  dplyr::select(summer_bot_do, LakeID)

trends %>%
  mutate(doy = as.Date("2022-01-01") + doy - 1) %>%
  ggplot(aes(x = doy, y = trend, group = LakeID)) +
  geom_line(alpha=0.01)+
  facet_wrap(~Variable, scales = "free_y")
```

Lm

```{r}
met_trends_matched <- max_cor_dates %>%
  left_join(trends, by = c("LakeID", "max_doy" = "doy"), relationship = "many-to-many") %>%
  group_by(season, var) %>%
  rename(cor_date_var = var)

df_for_rf <- summer_bot_mean %>%
  left_join(met_trends_matched %>% 
              select(LakeID, trend, season, Variable, cor_date_var) %>%
              arrange(LakeID) %>%
              pivot_wider(names_from = Variable,
                          values_from = trend) %>%
              filter(cor_date_var == "Summer hypo. temperature"),
            by = "LakeID") %>%
  pivot_wider(names_from = season,
              values_from = Air_temp_C:Shortwave_mJm2) %>%
  left_join(mem %>% filter(var == "summer_bot_mean") %>% select(M, LakeID), by = "LakeID") %>%
  mutate(M_binary = ifelse(M > 0, "> 0", "<= 0"))

responses <- c("summer_bot_mean")
potential_drivers <- c("Air_temp_C_spring", "Air_temp_C_summer", "M")
mem_rf_df_bot_temp <- df_for_rf %>%
  select(all_of(c(responses, potential_drivers))) %>%
  na.omit() %>%
  mutate(target = "Bottom-water\ntemperature")
lm1 <- lm(summer_bot_mean ~ Air_temp_C_spring*M + Air_temp_C_summer*M, 
          data = mem_rf_df_bot_temp)
summary(lm1)

mem_rf_df_bot_temp %>%
  ggplot(aes(x = Air_temp_C_spring, y = summer_bot_mean, color = M)) +
  geom_point()

# Surface

df_for_rf <- summer_surf_mean %>%
  left_join(met_trends_matched %>% 
              select(LakeID, trend, season, Variable) %>%
              arrange(LakeID) %>%
              pivot_wider(names_from = Variable,
                          values_from = trend))  %>%
  filter(cor_date_var == "Summer epi. temperature") %>%
  pivot_wider(names_from = season,
              values_from = Air_temp_C:Shortwave_mJm2) %>%
  left_join(mem %>% select(M, LakeID, var) %>% filter(var == "summer_surf_mean")) %>%
  mutate(M_binary = ifelse(M > 0, "> 0", "<= 0"))

responses <- c("summer_surf_mean")
potential_drivers <- c("Air_temp_C_spring", "Air_temp_C_summer", "M")
mem_rf_df_bot_temp <- df_for_rf %>%
  select(all_of(c(responses, potential_drivers))) %>%
  na.omit() %>%
  mutate(target = "Surface-water\ntemperature")
lm1 <- lm(summer_surf_mean ~ Air_temp_C_spring*M + Air_temp_C_summer*M, 
          data = mem_rf_df_bot_temp)
summary(lm1)

# DO

df_for_rf <- summer_bot_do %>%
  left_join(met_trends_matched %>% 
              select(LakeID, trend, season, Variable) %>%
              arrange(LakeID) %>%
              pivot_wider(names_from = Variable,
                          values_from = trend))  %>%
  filter(cor_date_var == "Summer hypo. DO") %>%
  pivot_wider(names_from = season,
              values_from = Air_temp_C:Shortwave_mJm2) %>%
  left_join(mem %>% select(M, LakeID, var) %>% filter(var == "summer_bot_mean")) %>%
  mutate(M_binary = ifelse(M > 0, "> 0", "<= 0"))

responses <- c("summer_bot_do")
potential_drivers <- c("Air_temp_C_spring", "Air_temp_C_summer", "M")
mem_rf_df_bot_temp <- df_for_rf %>%
  select(all_of(c(responses, potential_drivers))) %>%
  na.omit() %>%
  mutate(target = "Bottom-water\ndissolved oxygen")
lm1 <- lm(summer_bot_do ~ Air_temp_C_spring*M + Air_temp_C_summer*M, 
          data = mem_rf_df_bot_temp)
summary(lm1)
```

```{r}
df_for_rf <- summer_bot_mean %>%
  left_join(met_trends_matched %>% 
              select(LakeID, trend, season, Variable) %>%
              arrange(LakeID) %>%
              pivot_wider(names_from = Variable,
                          values_from = trend))  %>%
  filter(cor_date_var == "Summer hypo. temperature") %>%
  pivot_wider(names_from = season,
              values_from = Air_temp_C:Shortwave_mJm2) %>%
  left_join(mem %>% select(M, LakeID, var) %>% filter(var == "summer_bot_mean")) %>%
  mutate(M_binary = ifelse(M > 0, "> 0", "<= 0"))

responses <- c("summer_bot_mean", "M_binary")
potential_drivers <- c("Air_temp_C_spring", "Air_temp_C_summer", "Wind_ms_spring",
                       "Wind_ms_summer", "Shortwave_mJm2_spring",
                       "Shortwave_mJm2_summer")
mem_rf_df_bot_temp <- df_for_rf %>%
  select(all_of(c(responses, potential_drivers))) %>%
  na.omit() %>%
  mutate(target = "Bottom-water\ntemperature")
rf1 <- randomForest(summer_bot_mean ~ Air_temp_C_spring + Air_temp_C_summer + 
                      Wind_ms_spring + Wind_ms_summer + Shortwave_mJm2_spring + 
                      Shortwave_mJm2_summer,
                    data = mem_rf_df_bot_temp %>%
                      filter(M_binary == "<= 0"), 
                    ntree = 1000, 
                    importance = T)
rf2 <- randomForest(summer_bot_mean ~ Air_temp_C_spring + 
                      Air_temp_C_summer + Wind_ms_spring + Wind_ms_summer + 
                      Shortwave_mJm2_spring + Shortwave_mJm2_summer,
                    data = mem_rf_df_bot_temp %>%
                      filter(M_binary == "> 0"), 
                    ntree = 1000, 
                    importance = T)
ImpData_rf1 <- as.data.frame(importance(rf1)) %>%
  mutate(Var.Names = row.names(.)) %>%
  mutate(target = "Bottom-water\ntemperature\n(M <= 0)")
ImpData_rf2 <- as.data.frame(importance(rf2)) %>%
  mutate(Var.Names = row.names(.)) %>%
  mutate(target = "Bottom-water\ntemperature\n(M > 0)")
ImpData_rf2 %>%
  rbind(ImpData_rf1) %>%
  ggplot(aes(x = `%IncMSE`, y = Var.Names)) +
  geom_col() +
  theme_bw() +
  facet_wrap(~target)

mem_rf_df_bot_temp %>%
  ggplot(aes(x = Air_temp_C_spring, y = summer_bot_mean)) +
  geom_point()+
  facet_wrap(~M_binary) 
partialPlot(rf2, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "> 0")), "Air_temp_C_summer")
partialPlot(rf2, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "> 0")), "Air_temp_C_spring")
partialPlot(rf1, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "<= 0")), "Air_temp_C_summer")
partialPlot(rf1, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "<= 0")), "Air_temp_C_spring")
```

Repeat for DO

```{r}
df_for_rf <- summer_bot_do %>%
  left_join(met_trends_matched %>% 
              select(LakeID, trend, season, Variable) %>%
              arrange(LakeID) %>%
              pivot_wider(names_from = Variable,
                          values_from = trend))  %>%
  filter(cor_date_var == "Summer hypo. DO") %>%
  pivot_wider(names_from = season,
              values_from = Air_temp_C:Shortwave_mJm2) %>%
  left_join(mem %>% select(M, LakeID, var) %>% filter(var == "summer_bot_mean")) %>%
  mutate(M_binary = ifelse(M > 0, "> 0", "<= 0"))

responses <- c("summer_bot_do", "M_binary")
potential_drivers <- c("Air_temp_C_spring", "Air_temp_C_summer", "Wind_ms_spring",
                       "Wind_ms_summer", "Shortwave_mJm2_spring",
                       "Shortwave_mJm2_summer")
mem_rf_df_bot_temp <- df_for_rf %>%
  select(all_of(c(responses, potential_drivers))) %>%
  na.omit() %>%
  mutate(target = "Bottom-water\ndissolved oxygen")
rf1 <- randomForest(summer_bot_do ~ Air_temp_C_spring + Air_temp_C_summer + 
                      Wind_ms_spring + Wind_ms_summer + Shortwave_mJm2_spring + 
                      Shortwave_mJm2_summer,
                    data = mem_rf_df_bot_temp %>%
                      filter(M_binary == "<= 0"), 
                    ntree = 1000, 
                    importance = T)
rf2 <- randomForest(summer_bot_do ~ Air_temp_C_spring + 
                      Air_temp_C_summer + Wind_ms_spring + Wind_ms_summer + 
                      Shortwave_mJm2_spring + Shortwave_mJm2_summer,
                    data = mem_rf_df_bot_temp %>%
                      filter(M_binary == "> 0"), 
                    ntree = 1000, 
                    importance = T)
ImpData_rf1 <- as.data.frame(importance(rf1)) %>%
  mutate(Var.Names = row.names(.)) %>%
  mutate(target = "Bottom-water\nDO\n(M <= 0)")
ImpData_rf2 <- as.data.frame(importance(rf2)) %>%
  mutate(Var.Names = row.names(.)) %>%
  mutate(target = "Bottom-water\nDO\n(M > 0)")
ImpData_rf2 %>%
  rbind(ImpData_rf1) %>%
  ggplot(aes(x = `%IncMSE`, y = Var.Names)) +
  geom_col() +
  theme_bw() +
  facet_wrap(~target)

mem_rf_df_bot_temp %>%
  ggplot(aes(x = Air_temp_C_summer, y = summer_bot_do)) +
  geom_point()+
  facet_wrap(~M_binary) 
```
Surface temp

```{r}
df_for_rf <- summer_surf_mean %>%
  left_join(met_trends_matched %>% 
              select(LakeID, trend, season, Variable) %>%
              arrange(LakeID) %>%
              pivot_wider(names_from = Variable,
                          values_from = trend))  %>%
  filter(cor_date_var == "Summer epi. temperature") %>%
  pivot_wider(names_from = season,
              values_from = Air_temp_C:Shortwave_mJm2) %>%
  left_join(mem %>% select(M, LakeID, var) %>% filter(var == "summer_surf_mean")) %>%
  mutate(M_binary = ifelse(M > 0, "> 0", "<= 0"))

responses <- c("summer_surf_mean", "M_binary")
potential_drivers <- c("Air_temp_C_spring", "Air_temp_C_summer", "Wind_ms_spring",
                       "Wind_ms_summer", "Shortwave_mJm2_spring",
                       "Shortwave_mJm2_summer")
mem_rf_df_bot_temp <- df_for_rf %>%
  select(all_of(c(responses, potential_drivers))) %>%
  na.omit() %>%
  mutate(target = "Surface-water\ntemperature")
rf1 <- randomForest(summer_surf_mean ~ Air_temp_C_spring + Air_temp_C_summer + 
                      Wind_ms_spring + Wind_ms_summer + Shortwave_mJm2_spring + 
                      Shortwave_mJm2_summer,
                    data = mem_rf_df_bot_temp %>%
                      filter(M_binary == "<= 0"), 
                    ntree = 1000, 
                    importance = T)
rf2 <- randomForest(summer_surf_mean ~ Air_temp_C_spring + 
                      Air_temp_C_summer + Wind_ms_spring + Wind_ms_summer + 
                      Shortwave_mJm2_spring + Shortwave_mJm2_summer,
                    data = mem_rf_df_bot_temp %>%
                      filter(M_binary == "> 0"), 
                    ntree = 1000, 
                    importance = T)
ImpData_rf1 <- as.data.frame(importance(rf1)) %>%
  mutate(Var.Names = row.names(.)) %>%
  mutate(target = "Surface-water\ntemperature\n(M <= 0)")
ImpData_rf2 <- as.data.frame(importance(rf2)) %>%
  mutate(Var.Names = row.names(.)) %>%
  mutate(target = "Surface-water\ntemperature\n(M > 0)")
ImpData_rf2 %>%
  rbind(ImpData_rf1) %>%
  ggplot(aes(x = `%IncMSE`, y = Var.Names)) +
  geom_col() +
  theme_bw() +
  facet_wrap(~target)

partialPlot(rf2, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "> 0")), "Air_temp_C_summer")
partialPlot(rf2, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "> 0")), "Air_temp_C_spring")
partialPlot(rf1, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "<= 0")), "Air_temp_C_summer")
partialPlot(rf1, as.data.frame(mem_rf_df_bot_temp %>%
                      filter(M_binary == "<= 0")), "Air_temp_C_spring")
```

