---
title: "ISIMIP analysis"
author: "Abby Lewis"
date: "2024-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ncdf4)
library(tidyverse)
library(lubridate)
library(rLakeAnalyzer)
source("../Data processing/thermo.depth.density.R")
source("correlations_doy.R")

all <- read.csv("../Compiled data/Correlations - 30 day rolling mean.csv")
lat_long <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/1530/1/fadd3eaa25b5fdd1fc4efba70e660579")

all_export <- all %>%
  filter(grepl("temp", var)) %>%
  dplyr::select(LakeID) %>%
  unique() %>%
  left_join(lat_long) %>%
  dplyr::select(hylak_id, LakeName, LakeID, Latitude_DD, Longitude_DD) %>%
  filter(!is.na(hylak_id))

isimip <- nc_open('../External data/hydrolakes_id.nc') 
lakes <- ncvar_get(isimip,"id")
lat <- ncvar_get(isimip,"lat")
lon <- ncvar_get(isimip,"lon")
combined_df = data.frame(ID = as.vector(lakes),
                           lon = rep(lon,length(lat)),
                           lat = rep(lat,each=length(lon))
) %>%
  filter(!is.na(ID))
all_export2 <- all_export %>% 
  filter(hylak_id %in% combined_df$ID)
write.csv(all_export2, "../Data processing/lakes_for_isimip.csv", row.names = F)

lakes <- all_export2
climate <- read.csv("../Compiled data/ISIMIP_ERA5_temp_1981_2005.csv")%>%
  left_join(lat_long)

summer <- read.csv("../Compiled data/ISIMIP_summer_avgs_v3.csv") %>%
  pivot_wider(names_from = "Layer", values_from = "Temp_C", names_prefix = "Temp_C_")
```

```{r}
daily_temp <- climate %>%
  mutate(Date = as.Date(Date),
         Date = ifelse(Lat < 0, Date - months(6), Date),
         Date = as.Date(Date, origin = "1970-01-01")) %>%
  dplyr::select(-Lat, -Lon) %>%
  mutate(Year = year(Date))

many_lake_temp_sum <- summer %>%
  left_join(daily_temp) %>%
  mutate(doy = yday(Date),
         Year = ifelse(month(Date) >= 9, Year + 1, Year)) %>%
  group_by(LakeID) %>%
  arrange(Date) %>%
  mutate(Temp_C = zoo::rollmean(Temp_C, 30, align = "right", fill = NA))
# ---

epi_temp_roll <- correlations_doy(many_lake_temp_sum, 
                                    "Temp_C_EPI", "Temp_C", 
                                    "Summer epi. temperature ")

hypo_temp_roll <- correlations_doy(many_lake_temp_sum, 
                                    "Temp_C_HYPO", "Temp_C", 
                                    "Summer hypo. temperature ")

all <- epi_temp_roll %>%
  mutate(var = "Summer epi. temperature") %>%
  full_join(hypo_temp_roll %>%
              mutate(var = "Summer hypo. temperature")) 

write.csv(all, "../Compiled data/ISIMIP correlations - 30 day rolling mean v3.csv", row.names = F)
```

```{r}
alpha <- 0.05
all <- read.csv("../Compiled data/ISIMIP correlations - 30 day rolling mean v3.csv") %>%
  mutate(sig = ifelse(p < alpha, T, F))

sp <- yday(c("2022-03-01", "2022-05-31"))
su <- yday(c("2022-07-01", "2022-08-31"))

memory <- all %>% 
  filter(var %in% c("Summer epi. temperature",
                    "Summer hypo. temperature")) %>%
  mutate(var = factor(var, levels = c("Summer epi. temperature",
                                      "Summer hypo. temperature"),
                      labels = c("Summer epi.\ntemperature",
                                 "Summer hypo.\ntemperature")),
         season = ifelse(doy >= sp[1] & doy <= sp[2], "spring", 
                         ifelse(doy >= su[1] & doy <= su[2], "summer", NA))) %>%
  group_by(var) %>%
  mutate(p = wilcox.test(monthly_correlation)$p.value) %>%
  filter(!is.na(season)) %>%
  group_by(LakeID, var, season, p) %>%
  summarize(max = max(abs(monthly_correlation))) %>%
  pivot_wider(names_from = season, values_from = max) %>%
  mutate(M = (summer - spring)) 
```

```{r}
dates <- all %>% 
  filter(var %in% c("Summer epi. temperature",
                    "Summer hypo. temperature")) %>%
  mutate(var = factor(var, levels = c("Summer epi. temperature",
                                      "Summer hypo. temperature"),
                      labels = c("Summer\nepi. temperature",
                                 "Summer\nhypo. temperature")),
         season = ifelse(doy >= sp[1] & doy <= sp[2], "spring", 
                         ifelse(doy >= su[1] & doy <= su[2], "summer", NA))) %>%
  group_by(var) %>%
  mutate(p = wilcox.test(monthly_correlation)$p.value) %>%
  filter(!is.na(season)) %>%
  group_by(LakeID, var, season, p) %>%
  summarize(max_day = doy[which.max(abs(monthly_correlation))],
            max = max(abs(monthly_correlation))) %>%
  pivot_wider(names_from = season, values_from = c(max, max_day)) 

strat_onset <- read.csv("../Compiled data/ISIMIP_strat_onset_v3.csv")
```

```{r}
daily_temp %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID) %>%
  summarize(sd = abs(sd(Temp_C, na.rm = T))) %>%
  left_join(summer) %>%
  ggplot(aes(y = Temp_C_HYPO, x = sd, color = LakeID)) +
  geom_point()+
  scale_x_log10()+
  theme(legend.position = "none")+
  geom_smooth(method = "lm") +
  xlab("Standard deviation of air temperature\nin the 30 days prior to stratification onset")+
  ylab("Summer hypolimnetic temperature")

daily_temp %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID) %>%
  summarize(mean = mean(Temp_C, na.rm = T)) %>%
  left_join(summer) %>%
  ggplot(aes(y = Temp_C_HYPO, x = mean, color = LakeID)) +
  geom_point()+
  theme(legend.position = "none")+
  geom_smooth(method = "lm") +
  xlab("Air temperature\nin the 30 days prior to stratification onset")+
  ylab("Summer hypolimnetic temperature")
```

```{r}
strat_onset_annual <- read.csv("../Compiled data/ISIMIP_strat_onset_v3_yearly.csv") %>%
  mutate(strat_onset = yday(Date)) %>%
  select(-Date)

daily_temp %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset_annual) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID) %>%
  summarize(sd = abs(sd(Temp_C, na.rm = T))) %>%
  left_join(summer) %>%
  ggplot(aes(y = Temp_C_HYPO, x = sd, color = LakeID)) +
  geom_point()+
  scale_x_log10()+
  theme(legend.position = "none")+
  geom_smooth(method = "lm") +
  xlab("Standard deviation of air temperature\nin the 30 days prior to stratification onset")+
  ylab("Summer hypolimnetic temperature")

daily_temp %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset_annual) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID) %>%
  summarize(mean = mean(Temp_C, na.rm = T)) %>%
  left_join(summer) %>%
  ggplot(aes(y = Temp_C_HYPO, x = mean, color = LakeID)) +
  geom_point()+
  theme(legend.position = "none")+
  geom_smooth(method = "lm") +
  xlab("Air temperature\nin the 30 days prior to stratification onset")+
  ylab("Summer hypolimnetic temperature")

daily_temp %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset_annual) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID, strat_onset) %>%
  summarize(mean = mean(Temp_C, na.rm = T)) %>%
  left_join(summer) %>%
  ggplot(aes(x = strat_onset, y = mean, color = LakeID)) +
  geom_point()+
  theme(legend.position = "none")+
  geom_smooth(method = "lm") +
  xlab("Stratification onset date")+
  ylab("Air temperature\nin the 30 days prior to stratification onset")

p <- daily_temp %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID) %>%
  summarize(mean = mean(Temp_C, na.rm = T)) %>%
  left_join(summer) %>%
  left_join(strat_onset_annual) %>%
  ggplot(aes(x = strat_onset, y = mean, color = LakeID)) +
  geom_point()+
  theme(legend.position = "none")+
  geom_smooth(method = "lm") +
  xlab("Stratification onset date")+
  ylab("Air temperature in the 30 days prior\nto median stratification onset")
library(plotly)
ggplotly(p)

bf <- read.csv("../Compiled data/ISIMIP_bf_daily.csv")

bf %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset_annual) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID) %>%
  summarize(mean = mean(buoyancy_freq, na.rm = T)) %>%
  left_join(summer) %>%
  ggplot(aes(y = Temp_C_HYPO, x = mean, color = LakeID)) +
  geom_point()+
  scale_x_log10()+
  theme(legend.position = "none")+
  geom_smooth(method = "lm") +
  xlab("Buoyancy frequency in the 30 days prior to stratification onset")+
  ylab("Summer hypolimnetic temperature")

df <- bf %>%
  mutate(yday = yday(Date)) %>%
  left_join(strat_onset_annual) %>%
  filter(yday >= strat_onset - 30, 
         yday <= strat_onset) %>%
  group_by(Year, LakeID) %>%
  summarize(mean = mean(buoyancy_freq, na.rm = T)) %>%
  left_join(summer) 

cors <- df %>%
  group_by(LakeID) %>%
  summarize(cor = cor(Temp_C_HYPO, mean))
sum(cors$cor>0, na.rm = T)
sum(cors$cor<0, na.rm = T)

cors2 <- strat_onset_annual %>%
  left_join(summer) %>%
  group_by(LakeID) %>%
  summarize(cor = cor(Temp_C_HYPO, strat_onset))
sum(cors2$cor>0, na.rm = T)
sum(cors2$cor<0, na.rm = T)

jpeg("../Figures/correlation_plot.jpg", width = 5, height = 4, units = "in", res = 300)
strat_onset_annual %>%
  left_join(summer) %>%
  group_by(LakeID) %>%
  filter(n() >= 10) %>%
  ggplot(aes(y = Temp_C_HYPO, x = strat_onset, color = LakeID)) +
  geom_point()+
  geom_smooth(method = "lm") +
  xlab("Stratification onset date")+
  ylab("Summer hypolimnetic temperature")+
  theme_bw()+
  theme(legend.position = "none")+
  scale_color_viridis_d()
dev.off()
```