---
title: "ISIMIP analysis"
author: "Abby Lewis"
date: "2024-01-19"
output: html_document
---

Step 1: Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ncdf4)
library(tidyverse)
library(lubridate)
library(pracma)
library(rLakeAnalyzer)
library(furrr)
source("../Data processing/thermo.depth.density.R")
source("correlations_doy.R")

#Load data
hylak_ref <- nc_open("../External data/hydrolakes_id.nc")
files <- list.files("../External data/files_gotm/")

#Read in all files
load_gotm_file <- function(file){
  open <- nc_open(paste0("../External data/files_gotm/",file))
  isimip_id <- sub("20crv3-era5_historical_obsclim_gotm_", "", 
                sub("_daily_1901_2021.nc", "", file))
  Lon <- ncvar_get(open,"lon")
  Lon <- ifelse(Lon > 180, -(360 - Lon), Lon)
  Lat <- ncvar_get(open,"lat")
  time <- ncvar_get(open,"time")
  date <- as.Date("1881-01-01")+seconds(time)
  depth <- ncvar_get(open,"z")
  t_vector <- ncvar_get(open,"temp")
  fillvalue <- open[["var"]][["temp"]][["missval"]]
  t_vector[t_vector == fillvalue] <- NA
  hylak_id_df <- ncvar_get(hylak_ref,"id")
  hylak_lon <- ncvar_get(hylak_ref,"lon")
  hylak_lat <- ncvar_get(hylak_ref,"lat")
  hylak_id <- hylak_id_df[which(hylak_lon == c(Lon)), 
                          which(hylak_lat == c(Lat))]
  
  #Loop through lakes and add temp data based on lat/lon
  combined_t_df <- data.frame(hylak_id = rep(hylak_id, dim(depth)[1]*dim(depth)[2]),
                             Date = rep(date, each = dim(depth)[1]),
                             Depth_m = -c(depth), #I want positive depths
                             Temp_C = c(t_vector),
                             Lon = Lon,
                             Lat = Lat
                             )
  return(combined_t_df)
}

all_gotm <- map(files, load_gotm_file) %>%
  bind_rows() %>%
  filter(year(Date) >= 1980)
```


Step 2: Interpolate

```{r}
#Prep for interpolation
to_profiles_cleaning <- all_gotm %>%
  filter(!is.na(Temp_C)) %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(hylak_id, Date) %>% 
  filter(length(unique(Depth_m)) > 2) %>% #Need at least three depths
  mutate(Date = as.Date(Date)) %>%
  arrange(hylak_id, Date, Depth_m) %>%
  ungroup()

to_profiles_summer <- to_profiles_cleaning %>%
  mutate(Date = as.Date(Date, origin = "1970-01-01")) %>%
  mutate(hylak_id = as.numeric(hylak_id)) %>%
  filter(((Lat > 0) & 
            yday(Date) >= yday("2022-07-01") & 
            yday(Date) <= yday("2022-08-31")) |
           ((Lat < 0) &
              yday(Date) >= yday("2022-01-01") & 
              yday(Date) <= yday("2022-02-28"))) 

#Function to interpolate temeprature profiles to 1m resolution
interp_t <- function(lake, to_profiles_summer){
  alldates <- to_profiles_summer %>% 
    dplyr::select(hylak_id, Date, Depth_m, Temp_C) %>%
    filter(hylak_id == lake) %>%
    dplyr::select(Date) %>% 
    distinct() %>%
    unlist() %>% 
    as.vector()
  
  lake_data <- to_profiles_summer %>%
    filter(hylak_id == lake)
  
  interpolatedvalues.t <- furrr::future_map(alldates, 
                                            run_all_dates_t, 
                                            lake_data, 
                                            lake) |> 
    list_rbind()
  
  return(interpolatedvalues.t)
}

#Function to run across all dates
run_all_dates_t <- function(date_i, lake_data, lake){
  profile <- lake_data %>% 
    filter(Date == date_i)
  
  interpolated.depths <- seq(from=0, to= max(profile$Depth_m))
  
  datamatrix_<- data.frame(
    depths=profile$Depth_m,
    values=profile$Temp_C) %>%
    group_by(depths) %>% 
    dplyr::summarize(valuemean=mean(values)) %>% 
    ungroup() %>% 
    as.matrix()
  
  interpolated.dos <- pchip(xi= datamatrix_[,1], 
                            yi=datamatrix_[,2],
                            x= interpolated.depths)
  
  output = data.frame(hylak_id = lake,
                      Date = date_i,
                      Depth_m = interpolated.depths,
                      Temp_C = interpolated.dos)
  
  return(output)
}

#Interpolate all lakes/dates
plan(multisession, workers = 4)
laken <- to_profiles_summer$hylak_id %>% 
  unique()
interpolatedvalues.t <- furrr::future_map(laken,
                                          interp_t,
                                          to_profiles_summer) |> 
  list_rbind()
```


Step 2: Compile to epi/hypo means

```{r}
#Format
isimip_summer <- interpolatedvalues.t %>%
  mutate(Date = as.Date(Date, origin = "1970-01-01"),
         hylak_id = as.numeric(hylak_id)) %>%
  rename(LakeID = hylak_id)

#Calculate thermocline depth
thermo_depths <- isimip_summer %>%
  group_by(Date, LakeID)%>%
  dplyr::summarize(epi_depth = meta.depths(Temp_C, Depth_m, mixed.cutoff = 0)[1],
            hypo_depth = meta.depths(Temp_C, Depth_m, mixed.cutoff = 0)[2],
            max_depth = max(Depth_m),
            thermo = thermo.depth.density(Temp_C, #use custom density threshold function
                                          Depth_m, 
                                          mixed.cutoff = 0.1, 
                                          seasonal = F))%>% 
  mutate(Year = year(Date),
         unstrat = as.numeric(is.na(thermo))) %>%
  group_by(Year, LakeID)%>%
  dplyr::summarize(epi_depth = mean(epi_depth, na.rm = T),
            hypo_depth = mean(hypo_depth, na.rm = T),
            count_unstrat = sum(unstrat),
            n = n())

#Remove years with unstratified profiles and lakes where 10% of years have unstratified profiles
thermo_depths_sum <- thermo_depths%>%
  group_by(LakeID) %>%
  dplyr::mutate(count_unstrat_tot = sum(count_unstrat),
                n = sum(n))%>%
  filter((count_unstrat_tot/n) < 0.1,
         count_unstrat == 0) 

#Add thermocline depths
full_with_thermo <- isimip_summer %>%
  mutate(Year = year(Date)) %>%
  full_join(thermo_depths_sum) %>%
  filter(!is.na(epi_depth),
         !is.na(hypo_depth))

#Add discrete layer designations 
summer_layers <- full_with_thermo %>%
  mutate(Layer = ifelse(!is.na(Depth_m) & Depth_m < epi_depth, "EPI", NA),
         Layer = ifelse(!is.na(Depth_m) & Depth_m > hypo_depth, "HYPO" ,Layer)) %>%
  filter(!is.na(Layer))

#Identify stratification onset dates
strat_onset <- all_gotm %>%
  mutate(LakeID = as.numeric(hylak_id)) %>%
  select(-hylak_id)%>%
  filter(Lat > 0,
         month(Date) < 7) %>%
  group_by(Date, LakeID) %>%
  dplyr::summarize(max_depth = max(Depth_m),
            thermo = thermo.depth.density(Temp_C, Depth_m, mixed.cutoff = 0.1, seasonal = F))%>% 
  mutate(Year= year(Date),
         unstrat = as.numeric(is.na(thermo)))%>%
  filter(unstrat == 1,
         !max_depth > 1E19) %>%
  group_by(LakeID, Year) %>%
  filter(Date == max(Date),
         yday(Date) < yday("2022-08-30"))

#Then summarize to a median per lake
strat_onset_median <- strat_onset %>%
  group_by(LakeID) %>%
  summarize(strat_onset = median(yday(Date), na.rm = T))

#Export both
write.csv(strat_onset_median, "../Compiled data/ISIMIP_strat_onset_v3.csv", row.names = F)
write.csv(strat_onset, "../Compiled data/ISIMIP_strat_onset_v3_yearly.csv", row.names = F)

#Calculate averages in each layer and export
summer_avgs <- summer_layers %>%
  group_by(LakeID, Year, Layer) %>%
  dplyr::summarize(Temp_C = mean(Temp_C, na.rm = T))
write.csv(summer_avgs, "../Compiled data/ISIMIP_summer_avgs_v3.csv", row.names = F)

#Calculate buoyancy frequency and export
buoyancy <- interpolatedvalues.t %>%
  mutate(Date = as.Date(Date, origin = "1970-01-01")) %>%
  mutate(LakeID = as.numeric(hylak_id)) %>%
  group_by(Date, LakeID) %>%
  dplyr::summarize(buoyancy_freq = max(buoyancy.freq(Temp_C,Depth_m),na.rm=T))
write.csv(buoyancy, "../Compiled data/ISIMIP_bf_daily.csv", row.names = F)
```


Step 3: Load air temp. data

```{r}
hylak_ref <- nc_open("../External data/hydrolakes_id.nc")
files <- list.files("../External data/lake_tas/")

load_tas_file <- function(file){
  test <- read_tsv(paste0("../External data/lake_tas/",file),
                   col_names = c("Date", "Time", "Temp_C"),
                   show_col_types = FALSE)
  isimip_id <- sub("20crv3-era5_historical_obsclim_lake_", "", 
                sub("_daily_1901_2021.csv", "", file))
  
  #Find hydrolakes ID
  nc_file <- nc_open(paste0("../External data/files_gotm/20crv3-era5_historical_obsclim_gotm_", 
                            isimip_id, "_daily_1901_2021.nc"))
  Lon <- ncvar_get(nc_file,"lon")
  Lon <- ifelse(Lon > 180, -(360 - Lon), Lon)
  Lat <- ncvar_get(nc_file,"lat")
  hylak_id_df <- ncvar_get(hylak_ref,"id")
  hylak_lon <- ncvar_get(hylak_ref,"lon")
  hylak_lat <- ncvar_get(hylak_ref,"lat")
  hylak_id <- hylak_id_df[which(hylak_lon == c(Lon)), 
                          which(hylak_lat == c(Lat))]
  
  #Add temp data based on lat/lon
  combined_t_df <- data.frame(hylak_id = rep(hylak_id, nrow(test)),
                             Date = test$Date,
                             Temp_C = test$Temp_C - 273.15,
                             Lon = Lon,
                             Lat = Lat
                             )
  return(combined_t_df)
}

all_tas <- map(files, load_tas_file) %>%
  bind_rows() %>%
  filter(year(Date) >= 1980)

write.csv(all_tas, "../Compiled data/ISIMIP_ERA5_temp_1981_2005.csv", row.names = F)
```


Step 4: Calculate rolling mean correlations

```{r}
isimip <- nc_open('../External data/hydrolakes_id.nc') 
lakes <- ncvar_get(isimip,"id")
lat <- ncvar_get(isimip,"lat")
lon <- ncvar_get(isimip,"lon")
combined_df = data.frame(ID = as.vector(lakes),
                           lon = rep(lon,length(lat)),
                           lat = rep(lat,each=length(lon))
) %>%
  filter(!is.na(ID))

climate <- #read.csv("../Compiled data/ISIMIP_ERA5_temp_1981_2005.csv") %>%
  all_tas

summer <- #read.csv("../Compiled data/ISIMIP_summer_avgs_v3.csv") %>%
  summer_avgs %>%
  pivot_wider(names_from = "Layer", values_from = "Temp_C", names_prefix = "Temp_C_")

daily_temp <- climate %>%
  mutate(Date = as.Date(Date),
         Date = ifelse(Lat < 0, Date - months(6), Date),
         Date = as.Date(Date, origin = "1970-01-01")) %>%
  dplyr::select(-Lat, -Lon) %>%
  mutate(Year = year(Date)) %>%
  rename(LakeID = hylak_id)

many_lake_temp_sum <- summer %>%
  left_join(daily_temp) %>%
  mutate(doy = yday(Date),
         Year = ifelse(month(Date) >= 9, Year + 1, Year)) %>%
  group_by(LakeID) %>%
  arrange(Date) %>%
  mutate(Temp_C = zoo::rollmean(Temp_C, 30, align = "right", fill = NA))
# ---

epi_temp_roll <- correlations_doy(many_lake_temp_sum, 
                                    "Temp_C_EPI", "Temp_C", 
                                    "Summer epi. temperature ")

hypo_temp_roll <- correlations_doy(many_lake_temp_sum, 
                                    "Temp_C_HYPO", "Temp_C", 
                                    "Summer hypo. temperature ")

all <- epi_temp_roll %>%
  mutate(var = "Summer epi. temperature") %>%
  full_join(hypo_temp_roll %>%
              mutate(var = "Summer hypo. temperature")) 

write.csv(all, "../Compiled data/ISIMIP correlations - 30 day rolling mean v3.csv", row.names = F)
```

