---
title: "Air temp analysis"
author: "Abby Lewis"
date: "2023-05-22"
output: html_document
---

This file analyzes the effect of variation in air temperature on hypolimnetic temperature and DO.

Table of contents: Step 1: Load packages and data Step 2: Generate temp anomaly summary fig Step 3: Analyze the effect of monthly air temperature on hypolimnetic DO, VHOD, and temp dynamics

Step 1: Load packages and data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(mosaic)
library(ggallin)
library(ppcor)
library(multcompView)
library(ggpubr)
library(viridis)
library(MASS)
library(see)
source("monthly_correlations.R")
source("lmer_functions.R")

#Load saved data
with_temp = read.csv("../Compiled data/All_data_annual AF.csv")
lat_long <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/1530/1/fadd3eaa25b5fdd1fc4efba70e660579")

# Make a directory for Figures if there isn't one
if (!dir.exists("../Figures")){dir.create("../Figs")}
```

Step 4: Rolling means

```{r}
library(rMR)
daily_temp_raw <- read.csv("../Compiled data/historical_temp_output_era5_daily.csv")
daily_temp <- daily_temp_raw %>%
  mutate(Date = as.Date(Date),
         Date = ifelse(Lat < 0, Date - months(6), Date),
         Date = as.Date(Date, origin = "1970-01-01")) %>%
  dplyr::select(-Lat, -Lon) %>%
  mutate(Year = year(Date))
rm(daily_temp_raw)

many_lake_temp_sum <- with_temp %>%
  left_join(daily_temp) %>%
  mutate(doy = yday(Date),
         Year = ifelse(month(Date) >= 9, Year + 1, Year),
         DO_sat_EPI = ifelse(is.na(DO_sat_EPI),
                             rMR::DO.saturation(DO_mgL_EPI, 
                                                Temp_C_EPI, 
                                                elevation.m = Elevation_m,
                                                salinity = 0,
                                                salinity.units = "uS"),
                             DO_sat_EPI),
         DO_sat_HYPO = ifelse(is.na(DO_sat_HYPO),
                             rMR::DO.saturation(DO_mgL_HYPO, 
                                                Temp_C_HYPO, 
                                                elevation.m = Elevation_m,
                                                salinity = 0,
                                                salinity.units = "uS"),
                             DO_sat_HYPO)) %>%
  group_by(LakeID) %>%
  arrange(Date) %>%
  mutate(Temp_C = zoo::rollmean(Temp_C, 30, align = "right", fill = NA))
# ---

do_temp_roll <- many_lake_temp_sum %>%
  mutate(hypoxic = ifelse(max(DO_mgL_HYPO, na.rm = T)<1,"yes","no"))%>%
  filter(hypoxic=="no") %>%
  monthly_correlations_doy("DO_mgL_HYPO", "Temp_C", "hypolimnetic DO", alpha = 0.001)

temp_demand_roll <- monthly_correlations_doy(many_lake_temp_sum, 
                                    "DO_demand_mgLd_HYPO", "Temp_C", 
                                    "Summer VHOD ", alpha = 0.001)

epi_temp_roll <- monthly_correlations_doy(many_lake_temp_sum, 
                                    "Temp_C_EPI", "Temp_C", 
                                    "Summer epi. temperature ", alpha = 0.001)

epi_do_roll <- monthly_correlations_doy(many_lake_temp_sum, 
                                    "DO_mgL_EPI", "Temp_C", 
                                    "Summer epi. DO ", alpha = 0.001)

epi_do_sat_roll <- monthly_correlations_doy(many_lake_temp_sum, 
                                    "DO_sat_EPI", "Temp_C", 
                                    "Summer epi. DO (saturation) ", alpha = 0.001)

hypo_do_sat_roll <- monthly_correlations_doy(many_lake_temp_sum, 
                                    "DO_sat_HYPO", "Temp_C", 
                                    "Summer hypo. DO (saturation) ", alpha = 0.001)

#I don't think worth including chl-a. Potentially a negative correlation in summer, no real other patterns
#epi_chla_roll <- monthly_correlations_doy(many_lake_temp_sum, 
#                                    "Chla_ugL_EPI", "Temp_C", 
#                                    "Summer epi. chl-a ", alpha = 0.001)
# I've also tried EPI TP and HYPO TP, no clear patterns

hypo_temp_roll <- monthly_correlations_doy(many_lake_temp_sum, 
                                    "Temp_C_HYPO", "Temp_C", 
                                    "Summer hypo. temperature ", alpha = 0.001)

all <- do_temp_roll %>%
  mutate(var = "Summer hypo. DO") %>%
  full_join(epi_temp_roll %>%
              mutate(var = "Summer epi. temperature")) %>%
  full_join(epi_do_roll %>%
              mutate(var = "Summer epi. DO")) %>%
  full_join(hypo_temp_roll %>%
              mutate(var = "Summer hypo. temperature")) %>%
  full_join(temp_demand_roll %>% 
              mutate(var = "Summer VHOD")) %>%
  full_join(epi_do_sat_roll %>%
              mutate(var = "Summer epi. DO sat")) %>%
  full_join(hypo_do_sat_roll %>%
              mutate(var = "Summer hypo. DO sat"))

write.csv(all, "../Compiled data/Correlations - 30 day rolling mean.csv", row.names = F)
```

```{r}
alpha <- 0.001
all <- read.csv("../Compiled data/Correlations - 30 day rolling mean.csv") %>%
  mutate(sig = ifelse(p < alpha, T, F))

#source("plot_single_var.R")
#epi_temp <- plot_single_var("Summer epi. temperature")
#epi_do_sat <- plot_single_var("Summer epi. DO sat")
#hypo_temp <- plot_single_var("Summer hypo. temperature")
#hypo_do <- plot_single_var("Summer hypo. DO")
#hypo_vhod <- plot_single_var("Summer VHOD")

sp <- yday(c("2022-03-01", "2022-05-31"))
su <- yday(c("2022-07-01", "2022-08-31"))

memory <- all %>% 
  filter(var %in% c("Summer epi. temperature",
                    "Summer epi. DO sat",
                    "Summer hypo. temperature",
                    "Summer VHOD",
                    "Summer hypo. DO")) %>%
  mutate(var = factor(var, levels = c("Summer epi. temperature",
                                      "Summer epi. DO sat",
                                      "Summer hypo. temperature",
                                      "Summer hypo. DO",
                                      "Summer VHOD"),
                      labels = c("Summer\nepi. temperature",
                                 "Summer\nepi. DO sat",
                                 "Summer\nhypo. temperature",
                                 "Summer\nhypo. DO",
                                 "Summer\nVHOD")),
         season = ifelse(doy >= sp[1] & doy <= sp[2], "spring", 
                         ifelse(doy >= su[1] & doy <= su[2], "summer", NA))) %>%
  group_by(var) %>%
  mutate(p = wilcox.test(monthly_correlation)$p.value) %>%
  filter(!is.na(season)) %>%
  group_by(LakeID, var, season, p) %>%
  summarize(max = max(abs(monthly_correlation))) %>%
  pivot_wider(names_from = season, values_from = max) %>%
  mutate(M = (summer - spring)) 

memory_plot <- memory %>%
  ggplot(aes(y = var, x = M, color = p < alpha))+
  geom_vline(xintercept = 0)+
  geom_boxplot()+
  annotate("text", x = -0.75, y = -0.5, label = "More correlated\nwith spring", 
           lineheight = .9, size = 3, hjust = 0)+
  annotate("text", x = 0.75, y = -0.5, label = "More correlated\nwith summer", 
           lineheight = .9, size = 3, hjust = 1)+
  theme_bw() +
  scale_y_discrete(limits=rev) +
  xlab("\n")+
  theme(axis.title.y = element_blank())+
  scale_color_manual(values = c("grey40","#0FA9E6"))+
  coord_cartesian(xlim = c(-0.65,0.65), ylim = c(1,5), clip = "off")

jpeg("../Figures/Monthly correlations - sum.jpg", width = 3, height = 2.5, res = 300, units = "in")
memory_plot + theme(legend.position = "none")
dev.off()

jpeg("../Figures/Monthly correlations - sum long.jpg", width = 3, height = 3, res = 300, units = "in")
memory %>%
  ggplot(aes(y = var, x = M, color = p < alpha))+
  geom_vline(xintercept = 0)+
  geom_boxplot()+
  annotate("text", x = -0.75, y = -0.5, label = "More correlated\nwith spring", 
           lineheight = .9, size = 3, hjust = 0)+
  annotate("text", x = 0.75, y = -0.5, label = "More correlated\nwith summer", 
           lineheight = .9, size = 3, hjust = 1)+
  theme_bw() +
  scale_y_discrete(limits=rev) +
  xlab("\n")+
  theme(axis.title.y = element_blank())+
  scale_color_manual(values = c("grey40","#0FA9E6"))+
  coord_cartesian(xlim = c(-0.65,0.65), ylim = c(1,5), clip = "off") + 
  theme(legend.position = "none")
dev.off()

jpeg("../Figures/Monthly correlations - sum long concept.jpg", width = 3.5, height = 3.5, res = 300, units = "in")
memory %>%
  mutate(var = factor(var, 
                      levels = c("Summer\nepi. temperature",
                                 "Summer\nepi. DO sat",
                                 "Summer\nhypo. temperature",
                                 "Summer\nVHOD",
                                 "Summer\nhypo. DO"),
                      labels = c("Surface-water\ntemperature",
                                 "Surface-water\ndissolved oxygen (%)",
                                 "Bottom-water\ntemperature",
                                 "Bottom-water\noxygen demand",
                                 "Bottom-water\ndissolved oxygen (mg/L)")))%>%
  group_by(var) %>%
  mutate(color = ifelse(p > alpha, "Insignificant", 
                        ifelse(median(M) > 0, "> 0", "< 0")),
         color = factor(color, levels = c("< 0", "Insignificant", "> 0"))) %>%
  ggplot(aes(y = var, x = M, color = color))+
  geom_vline(xintercept = 0)+
  geom_boxplot()+
  annotate("text", x = -0.75, y = -0.5, label = "More correlated\nwith spring", 
           lineheight = .9, size = 3, hjust = 0)+
  annotate("text", x = 0.75, y = -0.5, label = "More correlated\nwith summer", 
           lineheight = .9, size = 3, hjust = 1)+
  theme_bw() +
  scale_y_discrete(limits=rev, position = "right") +
  xlab("\n")+
  theme(axis.title.y = element_blank(),
        legend.position = "top",
        legend.justification='left',
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8))+
  scale_color_manual(values = c("#25469a","grey70", "#c16586"), name = "Boxplot color")+
  coord_cartesian(xlim = c(-0.65,0.65), ylim = c(1,5), clip = "off")
dev.off()

jpeg("../Figures/Monthly correlations - sum long concept v2.jpg", width = 3.5, height = 3, res = 600, units = "in")
memory %>%
  filter(!var == "Summer\nepi. DO sat") %>%
  group_by(var) %>%
  mutate(n = length(unique(LakeID)),
         var = paste0(var, " (n = ",n,")")) %>%
  mutate(var = factor(var, 
                      levels = c("Summer\nepi. temperature (n = 413)",
                                 "Summer\nhypo. temperature (n = 368)",
                                 "Summer\nVHOD (n = 194)",
                                 "Summer\nhypo. DO (n = 286)"),
                      labels = c("Surface-water\ntemperature (n = 413)",
                                 "Bottom-water\ntemperature (n = 368)",
                                 "Bottom-water oxygen\ndemand  (n = 194)",
                                 "Bottom-water dissolved\noxygen (n = 286)")))%>%
  group_by(var) %>%
  mutate(color = ifelse(p > alpha, "Insignificant", 
                        ifelse(median(M) > 0, "median > 0", "median < 0")),
         color = factor(color, levels = c("median < 0", "Insignificant", "median > 0"))) %>%
  ggplot(aes(y = var, x = M, color = color))+
  geom_vline(xintercept = 0, color = "grey70")+
  geom_boxplot()+
  annotate("text", x = -0.7, y = 5, label = "More correlated\nwith spring", 
           lineheight = .9, size = 3, hjust = 0, color = "#25469a")+
  annotate("text", x = 0.7, y = 5, label = "More correlated\nwith summer", 
           lineheight = .9, size = 3, hjust = 1, color = "#c16586")+
  theme_bw() +
  ggtitle("\n")+
  scale_y_discrete(limits=rev, position = "right") +
  xlab("Relative correlation with summer\nvs. spring air temperature")+
  guides(color = guide_legend(nrow = 2))+
  theme(axis.title.y = element_blank(),
        axis.title.x = element_text(size= 8),
        legend.position = "none",
        legend.text = element_text(size = 8),
        legend.key.size = unit(1, "line"),
        legend.title = element_text(size = 8),
        legend.margin=margin(c(0,0,0,0)),
        legend.box.margin=margin(t = -2,l = 0, r = 0, b = -5),
        #axis.text.y=element_text(colour=c("#25469a","#25469a","#25469a","#c16586"))
        )+
  scale_color_manual(values = c("#25469a","#c16586"), name = paste0("Boxplot color\n(p < ", alpha, ")"))+
  coord_cartesian(xlim = c(-0.65,0.65), ylim = c(1,4), clip = "off")
dev.off()

library(patchwork)
ggarrange(epi_temp +
            ylim(-0.5, 0.75)+
            theme(axis.title.x = element_blank(),
                  axis.ticks.x = element_blank(),
                  axis.text.x = element_blank()),
          epi_do_sat +
            ylim(-0.5, 0.75)+
            theme(axis.title.y = element_blank(),
                  axis.title.x = element_blank(),
                  axis.ticks = element_blank(),
                  axis.text = element_blank()),
          memory_plot,
          hypo_temp +
            ylim(-0.5, 0.75),
          hypo_do + 
            ylim(-0.5, 0.75) +
            theme(axis.title.y = element_blank(),
                  axis.ticks.y = element_blank(),
                  axis.text.y = element_blank()),
          hypo_vhod + 
            ylim(-0.5, 0.75) +
            theme(axis.title.y = element_blank(),
                  axis.ticks.y = element_blank(),
                  axis.text.y = element_blank()),
          common.legend = T, legend = "bottom")
```


Plots of rolling means

```{r}
alpha <- 0.001
all <- read.csv("../Compiled data/Correlations - 30 day rolling mean.csv") %>%
  mutate(sig = ifelse(p < alpha, T, F))

group_fun <- function(sig) {
  group <- rep(1, length(sig))
  for (i in 2:length(sig)) {
    if(sig[i] == sig[i - 1]) {
      group[i] <- group[i - 1]
    } else {
      group[i] <- group[i - 1] + 1
    }
  }
  return(group)
}

all_plot <- all %>%
  group_by(var) %>%
  mutate(n = max(n), #Some lakes are missing from January because our air temp only goes back to 1980
         var = paste0(var, " (n = ",n,")")) %>%
  group_by(var, doy, sig) %>%
  summarise(mean = mean(monthly_correlation, na.rm = T),
            sd = sd(monthly_correlation, na.rm = T)) 

all_plot$group <- 1
for(i in 1:length(unique(all_plot$var))){
  all_plot$group[all_plot$var == unique(all_plot$var)[i]] <- group_fun(all_plot$sig[all_plot$var == unique(all_plot$var)[i]])
}

empty_df <- data.frame(var = unique(all_plot$var)) %>%
  filter(!var == "Summer epi. DO (n = 397)") %>%
  mutate(var = factor(var, levels = c("Summer epi. temperature (n = 413)",
                                      "Summer hypo. temperature (n = 368)",
                                      "Summer VHOD (n = 194)",
                                      "Summer hypo. DO (n = 286)")))

all_plot1 <- all_plot %>%
  mutate(DateTime = as.Date("2022-01-01") + days(doy))

all_plot2 <- all_plot %>%
  ungroup() %>%
  mutate(DateTime = as.Date("2022-01-01") + days(doy) + hours(23) + minutes(59),
         mean = ifelse(!is.na(lead(var)) & lead(var) == var, lead(mean), mean), #to get smooth lines
         sd = ifelse(lead(var) == var, lead(sd), sd))

colored_sd <- all_plot1 %>%
  full_join(all_plot2) %>%
  filter(var %in% c("Summer epi. temperature (n = 413)",
                    "Summer epi. DO sat (n = 423)",
                    "Summer hypo. temperature (n = 368)",
                    "Summer VHOD (n = 194)",
                    "Summer hypo. DO (n = 286)")) %>%
  mutate(var = factor(var, 
                      levels = c("Summer epi. temperature (n = 413)",
                                 "Summer epi. DO sat (n = 423)",
                                 "Summer hypo. temperature (n = 368)",
                                 "Summer hypo. DO (n = 286)",
                                 "Summer VHOD (n = 194)"),
                      labels = c("Summer epi. temperature, n = 413",
                                 "Summer epi. DO % sat, n = 423",
                                 "Summer hypo. temperature, n = 368",
                                 "Summer hypo. DO conc, n = 286",
                                 "Summer VHOD, n = 194")),
         layer = ifelse(grepl("epi", var), "epi", "hypo")) %>%
  ggplot() + 
  geom_hline(yintercept=0)+
  geom_vline(xintercept = as_datetime("2022-04-21"), color = "grey50", lty = "dashed")+
  geom_ribbon(aes(x = DateTime, 
                  ymin = mean - sd, ymax = mean + sd,
                  fill = sig, group = group),
              alpha = 0.5) +
  geom_line(aes(x = DateTime, y = mean)) +
  xlab("Air temperature date \n(right-aligned 30-day rolling mean)")+
  ylab("Correlation")+
  theme_bw()+
  scale_fill_manual(values = c("grey40","#0FA9E6"))+
  labs(fill = paste0("p < ",alpha)) +
  ggh4x::facet_manual(~var, design = "AB#
               CDE") +
  theme(legend.position = "bottom",
        strip.background = element_blank())

jpeg("../Figures/Monthly correlations - all daily roll mean sd.jpg", width = 8, height = 5, res = 300, units = "in")
colored_sd
dev.off()

jpeg("../Figures/Monthly correlations - all daily roll mean sd long.jpg", width = 5, height = 7, res = 300, units = "in")
colored_sd +
  ggh4x::facet_manual(~var, design = "AC
               BD
               #E")+
  xlim(as_datetime("2022-02-01"), as_datetime("2022-07-31"))
dev.off()
```

```{r}
alpha <- 0.0001
all <- read.csv("../Compiled data/Correlations - 30 day rolling mean.csv") %>%
  mutate(sig = ifelse(p < alpha, T, F))

group_fun <- function(sig) {
  group <- rep(1, length(sig))
  for (i in 2:length(sig)) {
    if(sig[i] == sig[i - 1]) {
      group[i] <- group[i - 1]
    } else {
      group[i] <- group[i - 1] + 1
    }
  }
  return(group)
}

all_plot <- all %>%
  group_by(var) %>%
  mutate(n = max(n), #Some lakes are missing from January because our air temp only goes back to 1980
         var = paste0(var, " (n = ",n,")")) %>%
  group_by(var, doy, sig) %>%
  summarise(mean = mean(monthly_correlation, na.rm = T),
            sd = sd(monthly_correlation, na.rm = T)) %>%
  mutate(sig = ifelse(abs(mean) > 0.2, T, F))

all_plot$group <- 1
for(i in 1:length(unique(all_plot$var))){
  all_plot$group[all_plot$var == unique(all_plot$var)[i]] <- group_fun(all_plot$sig[all_plot$var == unique(all_plot$var)[i]])
}

empty_df <- data.frame(var = unique(all_plot$var)) %>%
  filter(!var == "Summer epi. DO (n = 397)") %>%
  mutate(var = factor(var, levels = c("Summer epi. temperature (n = 413)",
                                      "Summer hypo. temperature (n = 368)",
                                      "Summer VHOD (n = 194)",
                                      "Summer hypo. DO (n = 286)")))

all_plot1 <- all_plot %>%
  mutate(DateTime = as.Date("2022-01-01") + days(doy))

all_plot2 <- all_plot %>%
  ungroup() %>%
  mutate(DateTime = as.Date("2022-01-01") + days(doy) + hours(23) + minutes(59),
         mean = ifelse(!is.na(lead(var)) & lead(var) == var, lead(mean), mean), #to get smooth lines
         sd = ifelse(lead(var) == var, lead(sd), sd))

colored_sd <- all_plot1 %>%
  full_join(all_plot2) %>%
  #filter(!var == "Summer epi. DO (n = 397)") %>%
  #mutate(var = factor(var, levels = c("Summer epi. temperature (n = 413)",
  #                                    "Summer hypo. temperature (n = 368)",
  #                                    "Summer VHOD (n = 194)",
  #                                    "Summer hypo. DO (n = 286)"))) %>%
  ggplot() + 
  #geom_rect(aes(xmin = as_datetime("2022-03-01"), 
  #              xmax = as_datetime("2022-05-31"), 
  #              ymin = -Inf, ymax = Inf), 
  #              fill = "grey80", alpha = 0.3, 
  #          data = empty_df) +
  #geom_rect(aes(xmin = as_datetime("2022-03-01") + days(30), 
  #              xmax = as_datetime("2022-05-31") + days(30), 
  #              ymin = -Inf, ymax = Inf), 
  #              fill = "grey80", alpha = 0.3, 
  #          data = empty_df) +
  #geom_rect(aes(xmin = as_datetime("2022-07-01"), xmax = as_datetime("2022-08-31"), 
  #              ymin = -Inf, ymax = Inf), 
  #              fill = "grey80", alpha = 0.3, 
  #          data = empty_df) +
  #geom_rect(aes(xmin = as_datetime("2022-07-01") + days(30), 
  #              xmax = as_datetime("2022-08-31") + days(30), 
  #              ymin = -Inf, ymax = Inf), 
  #              fill = "grey80", alpha = 0.3, 
  #          data = empty_df) +
  geom_hline(yintercept=0)+
  geom_vline(xintercept = as_datetime("2022-04-21"), color = "grey50", lty = "dashed")+
  geom_ribbon(aes(x = DateTime, 
                  ymin = mean - sd, ymax = mean + sd,
                  fill = sig, group = group),
              alpha = 0.5) +
  geom_line(aes(x = DateTime, y = mean)) +
  #geom_text(aes(x = as_datetime("2022-03-15") , y = 0.8, label = paste0("Spring")), 
  #          size = 3, color = "grey30",
  #          data = empty_df) +
  #geom_text(aes(x = as_datetime("2022-08-01") , y = 0.8, label = paste0("Summer")), 
  #          size = 3, color = "grey30",
  #          data = empty_df) +
  xlab("Air temperature date \n(right-aligned 30-day rolling mean)")+
  ylab("Correlation")+
  theme_bw()+
  scale_fill_manual(values = c("grey40","#0FA9E6"))+
  labs(fill = paste0("p < ",alpha)) +
  facet_wrap(~var, ncol = 2) 

jpeg("../Figures/Monthly correlations - all daily roll mean sd.jpg", width = 8, height = 5, res = 300, units = "in")
colored_sd
dev.off()
```

```{r}
all_plot1 %>%
  pivot_longer(cols = c(mean, sd)) %>%
  ggplot(aes(x = DateTime, y = value, color = name)) +
  geom_line()+
  facet_grid(cols = vars(var), rows = vars(name), scales = "free")

all_plot1 %>%
  group_by(var) %>%
  summarize(max = max(mean, na.rm = T),
            min = min(mean, na.rm = T),
            max_doy = doy[mean == max],
            min_doy = doy[mean == min]) %>%
  mutate(max_doy = as.Date("2022-01-01") + days(max_doy),
         min_doy = as.Date("2022-01-01") + days(min_doy))

dates_to_plot <- all %>%
  group_by(var, LakeID) %>%
  summarize(max = max(monthly_correlation, na.rm = T),
            min = min(monthly_correlation, na.rm = T),
            max_doy = doy[which.max(monthly_correlation)],
            min_doy = doy[which.min(monthly_correlation)]) 

library(ggridges)
dates_to_plot %>%
  left_join(lat_long) %>%
  filter(abs(Latitude_DD) > 30) %>%
  mutate(max_doy = ifelse(var == "Summer hypo. DO", min_doy, max_doy)) %>%
  ggplot(aes(x = as.Date("2022-01-01") + max_doy, 
             y = var))+
  geom_density_ridges(
      quantile_lines = TRUE,
      jittered_points = TRUE,
      alpha = 1,
      point_alpha = 1,
      fill = "grey96",
      point_color = "grey50",
      point_fill = "white",
      #aes(point_fill = Var),
      point_shape = 21,
      scale=0.9)+
  stat_density_ridges(
      quantile_lines = TRUE,
      geom = "density_ridges_gradient", calc_ecdf = TRUE,aes(fill = factor(after_stat(quantile))),
      scale=0.9)+
  xlab("Date of strongest correlation")+
  theme_bw()+
  xlim(as.Date(c("2022-01-01", "2022-08-31")))+
  scale_fill_viridis_d(alpha=0.1)+
  theme(legend.position = "none",
        axis.text.y = element_text(vjust = 0),
        axis.title.y = element_blank())
```

```{r}
sp <- yday(c("2022-02-01", "2022-05-31"))
su <- yday(c("2022-07-01", "2022-08-31"))
dates_to_plot <- all %>%
  mutate(season = ifelse(doy >= sp[1] & doy <= sp[2], "spring", 
                         ifelse(doy >= su[1] & doy <= su[2], "summer", NA))) %>%
  filter(!is.na(season)) %>%
  group_by(var, LakeID, season) %>%
  summarize(max_doy = doy[which.max(abs(monthly_correlation))]) 

dates_to_plot %>%
  left_join(lat_long) %>%
  #filter(abs(Latitude_DD) > 30) %>%
  ggplot(aes(x = as.Date("2022-01-01") + max_doy))+
  geom_histogram(binwidth = 2)+
  xlab("Date of strongest correlation")+
  theme_bw() +
  facet_grid(cols = vars(season), rows = vars(var), scales = "free_x")

date_start <- read_csv("../Compiled data/stratification_onset.csv")

dates <- date_start %>%
  group_by(LakeID) %>%
  mutate(Date_start = yday(Date_start)) %>%
  summarize(mean_start = mean(Date_start, na.rm = T),
            n = n()) %>%
  filter(n >= 10,
         !is.na(mean_start))

dates_to_plot %>%
  filter(season == "spring",
         var == "Summer hypo. temperature") %>%
  inner_join(dates) %>%
  ggplot(aes(x = mean_start, y = max_doy, group = LakeID)) +
  geom_abline(slope = 1) +
  geom_smooth(method = "lm")+
  geom_point()
```

```{r}
library(lterdatasampler)
ice_data <- ntl_icecover %>%
  left_join(lat_long, by = c("lakeid" = "LakeName")) %>%
  filter(year(ice_off)>1980) %>%
  mutate(ice_off = yday(ice_off))

all %>%
  filter(LakeID %in% c("31", "32")) %>%
  filter(var %in% c("Summer epi. temperature",
                    "Summer epi. DO sat",
                    "Summer hypo. temperature",
                    "Summer VHOD",
                    "Summer hypo. DO")) %>%
  ggplot()+
  geom_hline(yintercept=0)+
  geom_vline(aes(xintercept = ice_off, color = LakeID), data = ice_data, alpha = 0.2)+
  geom_line(aes(x = doy, y = monthly_correlation, color = LakeID)) +
  xlab("Air temperature date \n(right-aligned 30-day rolling mean)")+
  ylab("Correlation")+
  theme_bw()+
  scale_fill_manual(values = c("grey40","#0FA9E6"))+
  labs(fill = paste0("p < ",alpha)) +
  facet_wrap(~var) +
  theme(legend.position = "bottom",
        strip.background = element_blank())
```

```{r}
sp <- yday(c("2022-03-01", "2022-05-31"))
su <- yday(c("2022-07-01", "2022-08-31"))
memory <- all %>% 
  filter(var %in% c("Summer epi. temperature",
                    "Summer epi. DO sat",
                    "Summer hypo. temperature",
                    "Summer VHOD",
                    "Summer hypo. DO")) %>%
  mutate(var = factor(var, levels = c("Summer epi. temperature",
                                      "Summer epi. DO sat",
                                      "Summer hypo. temperature",
                                      "Summer VHOD",
                                      "Summer hypo. DO"),
                      labels = c("Summer epi. temperature",
                                 "Summer epi. DO sat",
                                 "Summer bottom-water\ntemperature",
                                 "Summer VHOD",
                                 "Summer bottom-water\ndissolved oxygen")),
         season = ifelse(doy >= sp[1] & doy <= sp[2], "spring", 
                         ifelse(doy >= su[1] & doy <= su[2], "summer", NA))) %>%
  group_by(var) %>%
  mutate(p = wilcox.test(monthly_correlation)$p.value) %>%
  filter(!is.na(season)) %>%
  group_by(LakeID, var, season, p) %>%
  summarize(max = max(abs(monthly_correlation))) %>%
  pivot_wider(names_from = season, values_from = max) %>%
  mutate(M = (summer - spring)) 

summer_avgs = read.csv("../Compiled data/summer_averages_wi.csv")%>%
  group_by(LakeID) %>%
  summarize(buoyancy_freq = median(buoyancy_freq, na.rm = T))

mean_temps <- with_temp %>%
  mutate(spring_temp = (temp_mar + temp_apr + temp_may)/3,
         summer_temp = (temp_july + temp_aug)/2) %>%
  group_by(LakeID) %>%
  summarize(spring_temp = mean(spring_temp, na.rm = T),
            summer_temp = mean(summer_temp, na.rm = T),
            annual_temp = mean(mean_temp, na.rm = T),
            tp = mean(TP_ugL_EPI, na.rm = T))

mem_plot <- memory %>%
  filter(var %in% c("Summer bottom-water\ntemperature",
                    "Summer bottom-water\ndissolved oxygen")) %>%
  left_join(summer_avgs) %>%
  left_join(lat_long) %>%
  mutate(SA_class = ifelse(SurfaceArea_ha > 100, "> 100 ha", "≤ 100 ha")) %>%
  filter(!is.na(SurfaceArea_ha)) %>%
  ggplot(aes(x = buoyancy_freq, y = M))+
  geom_hline(yintercept = 0)+
  geom_point(aes(color = SA_class, shape = SA_class))+
  geom_smooth(method = "lm", aes(color = SA_class))+
  ylab("Relative correlation with\nsummer vs. spring air temp")+
  #stat_cor(label.y = 0.7) +
  theme_bw() +
  xlab("Maximum buoyancy frequency (1/s)")+
  scale_color_manual(name = "Lake size", values = c("#202C39", "#65A47D"))+
  scale_shape_discrete(name = "Lake size")+
  facet_wrap(~var)+
  ylab("\n\n")+
  geom_text(x = 0, y = 0.65, label = "More correlated\nwith summer", 
           hjust = 1, lineheight = .9, size = 3, 
           data = data.frame(var = factor("Summer bottom-water\ntemperature",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  geom_text(x = 0, y = -0.65, label = "More correlated\nwith spring", 
           hjust = 1, lineheight = .9, size = 3, 
           data = data.frame(var = factor("Summer bottom-water\ntemperature",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  coord_cartesian(ylim = c(-0.65,0.65), clip = "off")

mem_plot
```

```{r}
mem_lm <- memory %>%
  left_join(summer_avgs) %>%
  left_join(mean_temps) %>%
  left_join(lat_long) %>%
  mutate(log_SA = log(SurfaceArea_ha),
         log_max_depth = log(MaximumDepth_m),
         log_tp = log(tp),
         temp_dif = summer_temp-spring_temp) %>%
  pivot_wider(names_from = var, values_from = M) %>%
  rename(epi_temp = `Summer epi. temperature`,
         hypo_temp = `Summer bottom-water\ntemperature`,
         hypo_do = `Summer bottom-water\ndissolved oxygen`,
         vhod = `Summer VHOD`,
         epi_do_sat = `Summer epi. DO sat`)

responses <- c("epi_temp")
potential_drivers <- c("log_SA", "log_max_depth", "buoyancy_freq")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(epi_temp ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
#Intercept only model is best

responses <- c("epi_do_sat")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(epi_do_sat ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
#intercept only model is equivalent

responses <- c("hypo_temp")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(hypo_temp ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
mod_lm_temp <- lm(hypo_temp~log_SA+buoyancy_freq+log_max_depth+log_max_depth:log_SA, 
             data = mem_lm_df) 
temp <- plot_effects_lm(mod_lm_temp,"Relative correlation\nsummer hypo. temp") 

responses <- c("hypo_do")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(hypo_do ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
mod_lm_do <- lm(hypo_do~log_SA+buoyancy_freq, data = mem_lm_df) 
do <- plot_effects_lm(mod_lm_do,"Relative correlation\nsummer hypo. DO") 

responses <- c("vhod")
mem_lm_df <- standardize_data(mem_lm,responses,potential_drivers)
fm1 <- lm(vhod ~ log_SA*log_max_depth*buoyancy_freq, 
          data = mem_lm_df,
          na.action = "na.fail")
dd <- MuMIn::dredge(fm1)
subset(dd, delta < 2)
#Intercept only model is best

#Plot temp and DO together
#Temp first
effects_temp = data.frame(summary(mod_lm_temp)$coefficients)%>%
  rename(std_error = Std..Error)
effects_temp$Var = row.names(effects_temp)
confs_temp = data.frame(confint(mod_lm_temp))
confs_temp$Var = row.names(confs_temp)
effects2_temp = effects_temp%>%
  left_join(confs_temp)%>%
  rename(xmin = X2.5..,
         xmax = X97.5..)
#DO
effects_do = data.frame(summary(mod_lm_do)$coefficients)%>%
  rename(std_error = Std..Error)
effects_do$Var = row.names(effects_do)
confs_do = data.frame(confint(mod_lm_do))
confs_do$Var = row.names(confs_do)
effects2_do = effects_do%>%
  left_join(confs_do)%>%
  rename(xmin = X2.5..,
         xmax = X97.5..)
#Combine
effects2 <- effects2_temp %>%
  mutate(name = "hypo_temp")%>%
  full_join(effects2_do %>% mutate(name = "hypo_do"))
comb <- effects2%>%
  filter(!Var=="(Intercept)")%>%
  mutate(Var = renamer(Var),
         Var = factor(Var, levels = Var[order(abs(Estimate[name == "hypo_temp"]))]))%>%
  mutate(name = factor(name, 
                       levels = c("hypo_temp",
                                  "hypo_do"),
                       labels = c("Summer bottom-water\ntemperature",
                                  "Summer bottom-water\ndissolved oxygen"))) %>%
  ggplot(aes(y = Var, x=Estimate))+
  geom_vline(xintercept = 0)+
  geom_point()+
  geom_errorbar(aes(xmin=xmin, xmax = xmax),width=0.1)+
  theme_bw()+
  xlab("Parameter estimate")+
  geom_text(x = -0.5, y = -0.8, label = "More correlated\nwith spring", 
           hjust = 0, lineheight = .9, size = 3, 
           data = data.frame(name = factor("Summer bottom-water\ntemperature",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  geom_text(x = 0.15, y = -0.8, label = "More correlated\nwith summer", 
           hjust = 1, lineheight = .9, size = 3, 
           data = data.frame(name = factor("Summer bottom-water\ndissolved oxygen",
                                          levels = c("Summer bottom-water\ntemperature",
                                                     "Summer bottom-water\ndissolved oxygen"))))+
  theme(axis.title.y = element_blank(),
        plot.margin = unit(c(5.5, 5.5, 10, 5.5), "pt"))+
  facet_wrap(~name)+
  coord_cartesian(ylim = c(1, 4), clip = F)

jpeg("../Figures/Memory drivers.jpg", res = 300, width = 5, height = 5.5, units = "in")
ggarrange(comb +
            ggtitle("Relative correlation with summer vs. spring air temp") +
            theme(plot.title = element_text(size = 11)),
          mem_plot + 
            guides(shape = guide_legend(override.aes = list(size = 3)))+
            theme(legend.position = "bottom",
                  legend.margin=margin(c(0,0,0,0))),
          nrow = 2, 
          align = "v", heights = c(1,1.4), labels = "auto", label.x = .1)+
  theme(plot.margin = margin(0.1,0.1,0.1,-1, "cm"))
dev.off()

comb
```


```{r}
many_lake_temp_sum <- with_temp %>%
  left_join(daily_temp) %>%
  mutate(doy = yday(Date),
         Year = ifelse(month(Date) >= 9, Year + 1, Year)) %>%
  group_by(LakeID) %>%
  arrange(Date) %>%
  mutate(Temp_C = zoo::rollmean(Temp_C, 30, align = "right", fill = NA))

jpeg("../Figures/Summer otsego.jpg", res = 300, width = 4, height = 4, units = "in")
many_lake_temp_sum %>%
  filter(LakeID == "124",
         doy == 225) %>%
  ggplot(aes(x = Temp_C, y = Temp_C_EPI))+
  geom_point()+
  xlab("Mean air temperature July 15 - August 14")+
  ggtitle("Otsego")+
  ylab("Summer epilimnetic temperature")+
  theme_bw()
dev.off()

jpeg("../Figures/Winter otsego.jpg", res = 300, width = 4, height = 4, units = "in")
many_lake_temp_sum %>%
  filter(LakeID == "124",
         doy == 59) %>%
  ggplot(aes(x = Temp_C, y = Temp_C_EPI))+
  geom_point()+
  xlab("Mean air temperature March 1 - March 30")+
  ggtitle("Otsego")+
  ylab("Summer epilimnetic temperature")+
  theme_bw()
dev.off()

jpeg("../Figures/Summer all.jpg", res = 300, width = 4, height = 4, units = "in")
epi_temp_roll %>%
  filter(doy == 225) %>%
  ggplot(aes(x = monthly_correlation, y = doy))+
  geom_density_ridges(
      quantile_lines = TRUE,
      jittered_points = TRUE,
      alpha = 1,
      point_alpha = 1,
      fill = "grey96",
      point_color = "grey50",
      point_fill = "white",
      #aes(point_fill = Var),
      point_shape = 21,
      scale=0.9)+
  stat_density_ridges(
      quantile_lines = TRUE,
      geom = "density_ridges", calc_ecdf = TRUE,
      scale=0.9, alpha = 0)+
  xlab("Spearman's correlation")+
  ylab("Density")+
  theme_bw()+
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),)+
  ggtitle("July 15 - August 14 air temp.")
dev.off()

jpeg("../Figures/Winter all.jpg", res = 300, width = 4, height = 4, units = "in")
epi_temp_roll %>%
  filter(doy == 58) %>%
  ggplot(aes(x = monthly_correlation, y = doy))+
  geom_density_ridges(
      quantile_lines = TRUE,
      jittered_points = TRUE,
      alpha = 1,
      point_alpha = 1,
      fill = "grey96",
      point_color = "grey50",
      point_fill = "white",
      #aes(point_fill = Var),
      point_shape = 21,
      scale=0.9)+
  stat_density_ridges(
      quantile_lines = TRUE,
      geom = "density_ridges", calc_ecdf = TRUE,
      scale=0.9, alpha = 0)+
  xlab("Spearman's correlation")+
  ylab("Density")+
  theme_bw()+
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),)+
  ggtitle("March 1 - March 30 air temp.")
dev.off()
```


