---
title: "Spring metrics"
author: "Abby Lewis"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

sen_slope_custom <- function(df,var){
  output = df%>%
    group_by(LakeID)%>%
    dplyr::summarize(n = n(),
              trend = NA,
              sig = NA,
              min_year = NA,
              max_year = NA)
  for(lake in unique(df$LakeID)){
    filt = df %>%
      filter(LakeID==lake) %>%
      mutate(date = as.POSIXct(paste0(Year,"-01-01"))) %>%
      ungroup()%>%
      dplyr::select(-Year)
    if(length(unique(year(filt$date)))>=15){#Only calculate a trend if there are 10 years of data
      sen = trend::sens.slope(filt[[var]])
      output$trend[output$LakeID==lake]<-sen$estimates[1]
      output$sig[output$LakeID==lake]<-sen$p.value[1]
      output$min_year[output$LakeID==lake]<-min(year(filt$date))
      output$max_year[output$LakeID==lake]<-max(year(filt$date))
      output$var <- var
    }
  }
  return(output)
}
```

Calculate relevant metrics of "spring"

-   Spring duration
-   Spring temp
-   Spring end date
-   Winter duration
-   Winter temp
-   Summer temp

```{r}
climate_era5 = read.csv("../Compiled data/historical_temp_output_era5.csv")

min(climate_era5$Year)
```

Woolway definition:

April trend / (mean of (May - March)/2)

```{r}
rates <- climate_era5 %>%
  filter(Year>=1980) %>%
  group_by(LakeID, Year) %>%
  summarize(sp_rate = (unique(Temp_C[Month == 5]) - unique(Temp_C[Month == 3]))/2,
            wi_rate = (unique(Temp_C[Month == 2]) - unique(Temp_C[Month == 12]))/2) %>%
  group_by(LakeID) %>%
  summarize(mean_sp_rate = mean(sp_rate),
            mean_wi_rate = mean(wi_rate))

april_trends <- climate_era5 %>% 
  filter(Year >= 1980,
         Month %in% c(4)) %>%
  group_by(Year, LakeID) %>%
  summarize(Temp_C = mean(Temp_C, na.rm = T)) %>%
  sen_slope_custom("Temp_C")

jan_trends <- climate_era5 %>% 
  filter(Year >= 1980,
         Month %in% c(1)) %>%
  group_by(Year, LakeID) %>%
  summarize(Temp_C = mean(Temp_C, na.rm = T)) %>%
  sen_slope_custom("Temp_C")

lat_long <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/1530/1/fadd3eaa25b5fdd1fc4efba70e660579")

woolway <- rates %>%
  full_join(april_trends %>% rename(apr_trend = trend) %>% select(LakeID, apr_trend)) %>%
  full_join(jan_trends %>% rename(jan_trend = trend) %>% select(LakeID, jan_trend)) %>%
  mutate(earlier_sp = -apr_trend/mean_sp_rate * 10 * 365.25 / 12,
         earlier_wi = -jan_trend/mean_wi_rate * 10 * 365.25 / 12,
         sp_duration = earlier_wi - earlier_sp) %>%
  left_join(lat_long)

summer_mean_sen <- read.csv("summer_hypo_temp_mean_trends.csv")

woolway %>%
  select(LakeID, earlier_sp, Country, StateOrProvince, mean_sp_rate) %>%
  filter(mean_sp_rate > 0.5) %>%
  mutate(Region = ifelse(StateOrProvince %in% c("Wisconsin", "Minnesota", "Michigan"),
                         "Midwest",
                         ifelse(StateOrProvince %in% c("Maine", "New York", "NH", "New Hampshire", "Vermont"), "NE", "Other"))) %>%
  full_join(summer_mean_sen) %>%
  ggplot(aes(x = earlier_sp, y = trend*10)) +
  geom_point(aes(color = Region)) +
  geom_smooth(method = "lm")+
  xlab("Change in timing of spring (d/decade)\n(positive = later, negative = earlier)")+
  ylab("Trend in bottom-water temperature (ºC/decade)")
```
The rate at which air temperatures warm during the spring (May-March) is correlated with bottom-water temps in WI, but I'm not sure why
Tried April-Feb and no patterns
```{r}
sp_rate_trends <- climate_era5 %>%
  filter(Year>=1980) %>%
  group_by(LakeID, Year) %>%
  summarize(sp_rate = (unique(Temp_C[Month == 5]) - unique(Temp_C[Month == 3]))/2) %>%
  sen_slope_custom("sp_rate")

sp_rate_trends %>%
  rename(spring_warming = trend) %>%
  select(LakeID, spring_warming) %>%
  left_join(lat_long) %>%
  mutate(Region = ifelse(StateOrProvince %in% c("Wisconsin", "Minnesota", "Michigan"),
                         "Midwest",
                         ifelse(StateOrProvince %in% c("Maine", "New York", "NH", "New Hampshire", "Vermont"), 
                                "NE", "Other"))) %>%
  full_join(summer_mean_sen) %>%
  ggplot(aes(x = spring_warming, y = trend*10)) +
  geom_point(aes(color = Region)) +
  geom_smooth(method = "lm")+
  xlab("Change in (May - March) air temperature (ºC/decade)")+
  ylab("Trend in bottom-water temperature (ºC/decade)")+
  facet_wrap(~Region)
```
