---
title: "Untitled"
author: "Abby Lewis"
date: "2023-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(trend) #switched from openair 7 Nov 2023

# Make a directory for Figures if there isn't one
if (!dir.exists("../Figures")){dir.create("../Figs")}
```

```{r}
full_with_thermo <- read_csv("../Compiled data/Stratified_period_data_with_thermo.csv")

summer_layers <- full_with_thermo%>%
  mutate(Layer = ifelse(!is.na(Depth_m)&Depth_m<epi_depth, "EPI", NA),
         Layer = ifelse(is.na(Depth_m)&!is.na(Interval)&Interval=="EPILIMNION","EPI",Layer),
         Layer = ifelse(!is.na(Depth_m)&Depth_m>hypo_depth,"HYPO",Layer),
         Layer = ifelse(is.na(Depth_m)&!is.na(Interval)&Interval=="HYPOLIMNION","HYPO",Layer),
         Layer = ifelse(!is.na(Depth_m)&Depth_m<hypo_depth&Depth_m>epi_depth, "META",Layer),
         Layer = ifelse(is.na(Depth_m)&!is.na(Interval)&Interval=="METALIMNION","META",Layer))%>%
  filter(!is.na(Layer))

for_sen <- summer_layers %>%
  filter(Layer == "HYPO", !is.na(Temp_C)) %>%
  mutate(Month = month(Date)) %>%
  group_by(LakeID, Month, Year)%>%
  dplyr::summarize(Temp_C = mean(Temp_C, na.rm = T))

all_data <- read.csv("../Compiled data/All_data_annual AF.csv")

#Function
sen_slope_custom <- function(df,var){
  output = df%>%
    group_by(LakeID)%>%
    dplyr::summarize(n = n(),
              trend = NA,
              sig = NA,
              min_year = NA,
              max_year = NA)
  for(lake in unique(df$LakeID)){
    filt = df %>%
      filter(LakeID==lake) %>%
      mutate(date = as.POSIXct(paste0(Year,"-01-01"))) %>%
      ungroup()%>%
      dplyr::select(-Year)
    if(length(unique(year(filt$date)))>=10){#Only calculate a trend if there are 10 years of data
      sen = trend::sens.slope(filt[[var]])
      output$trend[output$LakeID==lake]<-sen$estimates[1]
      output$sig[output$LakeID==lake]<-sen$p.value[1]
      output$min_year[output$LakeID==lake]<-min(year(filt$date))
      output$max_year[output$LakeID==lake]<-max(year(filt$date))
    }
  }
  return(output)
}

mar_sen <- sen_slope_custom(for_sen %>% filter(Month == 3),"Temp_C")
apr_sen <- sen_slope_custom(for_sen %>% filter(Month == 4),"Temp_C")
may_sen <- sen_slope_custom(for_sen %>% filter(Month == 5),"Temp_C")
jun_sen <- sen_slope_custom(for_sen %>% filter(Month == 6),"Temp_C")
jul_sen <- sen_slope_custom(for_sen %>% filter(Month == 7),"Temp_C")
aug_sen <- sen_slope_custom(for_sen %>% filter(Month == 8),"Temp_C")
sep_sen <- sen_slope_custom(for_sen %>% filter(Month == 9),"Temp_C")
oct_sen <- sen_slope_custom(for_sen %>% filter(Month == 10),"Temp_C")
mean_sen <- sen_slope_custom(all_data %>% filter(!is.na(strat_Temp_C_HYPO)), "strat_Temp_C_HYPO")
summer_mean_sen <- sen_slope_custom(all_data %>% filter(!is.na(Temp_C_HYPO)), "Temp_C_HYPO")
epi_sen <- sen_slope_custom(all_data %>% filter(!is.na(strat_Temp_C_EPI)), "strat_Temp_C_EPI")
summer_epi_sen <- sen_slope_custom(all_data %>% filter(!is.na(Temp_C_EPI)), "Temp_C_EPI")
summer_do_sen <- sen_slope_custom(all_data %>% filter(!is.na(DO_mgL_HYPO), DO_mgL_HYPO > 1), "DO_mgL_HYPO")
summer_af_sen <- sen_slope_custom(all_data %>% filter(!is.na(AF), AF > 0), "AF")
summer_vhod_sen <- sen_slope_custom(all_data %>% filter(!is.na(DO_demand_mgLd_HYPO)), "DO_demand_mgLd_HYPO")
summer_hypo_tp_sen <- sen_slope_custom(all_data %>% filter(!is.na(TP_ugL_HYPO)), "TP_ugL_HYPO")
summer_epi_tp_sen <- sen_slope_custom(all_data %>% filter(!is.na(TP_ugL_EPI)), "TP_ugL_EPI")
hypo_tp_sen <- sen_slope_custom(all_data %>% filter(!is.na(strat_TP_ugL_HYPO)), "strat_TP_ugL_HYPO")
epi_tp_sen <- sen_slope_custom(all_data %>% filter(!is.na(strat_TP_ugL_EPI)), "strat_TP_ugL_EPI")

all_trends <- may_sen %>%
  mutate(Month = 5) %>%
  full_join(jun_sen %>% mutate(Month = 6)) %>%
  full_join(jul_sen %>% mutate(Month = 7)) %>%
  full_join(aug_sen %>% mutate(Month = 8)) %>%
  full_join(sep_sen %>% mutate(Month = 9)) #%>%
  #full_join(oct_sen %>% mutate(Month = 10)) 

write.csv(all_trends, "hypo_temp_monthly.csv", row.names = F)
write.csv(mean_sen, "hypo_temp_mean_trends.csv", row.names = F)
write.csv(summer_do_sen, "summer_do_trends.csv", row.names = F)
write.csv(summer_af_sen, "summer_af_trends.csv", row.names = F)
write.csv(epi_sen, "epi_temp_trends.csv", row.names = F)
write.csv(summer_epi_sen, "summer_epi_temp_trends.csv", row.names = F)
write.csv(summer_vhod_sen, "summer_vhod_trends.csv", row.names = F)
write.csv(summer_mean_sen, "summer_hypo_temp_mean_trends.csv", row.names = F)
write.csv(summer_epi_tp_sen, "summer_epi_tp_trends.csv", row.names = F)
write.csv(summer_hypo_tp_sen, "summer_hypo_tp_trends.csv", row.names = F)
write.csv(epi_tp_sen, "epi_tp_trends.csv", row.names = F)
write.csv(hypo_tp_sen, "hypo_tp_trends.csv", row.names = F)

climate_era5 = read.csv("../Compiled data/historical_temp_output_era5.csv")
climate_era5_spring <- climate_era5 %>% 
  filter(Year > 1980,
         Month %in% c(3,4)) %>%
  group_by(Year, LakeID) %>%
  summarize(Temp_C = mean(Temp_C, na.rm = T))
spring_era5_trends <- sen_slope_custom(climate_era5_spring, "Temp_C")

climate_era5_summer <- climate_era5 %>% 
  filter(Year > 1980,
         Month %in% c(7,8)) %>%
  group_by(Year, LakeID) %>%
  summarize(Temp_C = mean(Temp_C, na.rm = T))
summer_era5_trends <- sen_slope_custom(climate_era5_summer, "Temp_C")
era5_seasons <- spring_era5_trends %>%
  rename(Spring = trend) %>%
  select(Spring, LakeID) %>%
  left_join(summer_era5_trends %>%
              rename(Summer = trend) %>%
              select(Summer, LakeID)) %>%
  mutate(source = "era5means")

era5_seasons %>%
  ggplot(aes(x = Spring, y = Summer)) +
  geom_point()
```

```{r}
hypo_mean <- read.csv("hypo_temp_mean_trends.csv") %>%
  rename(hypo_mean = trend) %>%
  select(hypo_mean, LakeID)
summer_hypo_mean <- read.csv("summer_hypo_temp_mean_trends.csv") %>%
  rename(summer_hypo_mean = trend) %>%
  select(summer_hypo_mean, LakeID)
epi_mean <- read.csv("epi_temp_trends.csv") %>%
  rename(epi_mean = trend) %>%
  select(epi_mean, LakeID)
summer_epi_mean <- read.csv("summer_epi_temp_trends.csv") %>%
  rename(summer_epi_mean = trend) %>%
  select(summer_epi_mean, LakeID)
narr <- read.csv('../Compiled data/climate_narr %>% filter(Year > 1980)_"Temp_C".csv')
jra55 <- read.csv('../Compiled data/climate_jra55 %>% filter(Year > 1980)_"Temp_C".csv')
era5 <- read.csv('../Compiled data/climate_era5 %>% filter(Year > 1980)_"Temp_C".csv')
narr_seas <- narr %>%
  group_by(LakeID) %>%
  summarize(Spring = mean(trend[Month %in% c(4)]),
            Summer = mean(trend[Month %in% c(8)])) %>%
  mutate(source = "narr")
jra55_seas <- jra55 %>%
  group_by(LakeID) %>%
  summarize(Spring = mean(trend[Month %in% c(4)]),
            Summer = mean(trend[Month %in% c(8)])) %>%
  mutate(source = "jra55")
era5_seas <- era5 %>%
  group_by(LakeID) %>%
  summarize(Spring = mean(trend[Month %in% c(4)]),
            Summer = mean(trend[Month %in% c(8)])) %>%
  mutate(source = "era5")

ALL <- era5_seas %>%
  full_join(era5_seasons) %>%
  full_join(narr_seas) %>%
  full_join(jra55_seas) %>%
  full_join(epi_mean) %>%
  full_join(hypo_mean) %>%
  full_join(summer_epi_mean) %>%
  full_join(summer_hypo_mean) %>%
  pivot_longer(cols = c("epi_mean", "hypo_mean", "summer_epi_mean", "summer_hypo_mean"),
               names_to = "layer", values_to = "water_temp") %>%
  pivot_longer(cols = c("Spring", "Summer"),
               names_to = "season", values_to = "air_temp")

library(ggpmisc)

jpeg("temp_trend_seasons.jpg", width = 6, height = 6, units = "in", res = 300)
trend_seasons <- ALL %>%
  filter(source == "era5",
         layer %in% c("summer_epi_mean", "summer_hypo_mean")) %>%
  mutate(layer = ifelse(layer == "summer_epi_mean", "Summer epilimnetic temp.", "Summer hypolimnetic temp.")) %>%
  mutate(season = ifelse(season == "Spring", "Spring air temp.", "Summer air temp.")) %>%
  filter(!is.na(air_temp), 
         !is.na(water_temp)) %>%
  ggplot(aes(x = air_temp, y = water_temp)) +
  geom_hline(yintercept = 0, color = "grey75") +
  geom_vline(xintercept = 0, color = "grey75") +
  geom_abline(slope = 1, color = "black")+
  geom_point() +
  geom_smooth(method = "lm", color = "hotpink", data = . %>% 
                filter((season == "Spring air temp." & layer == "Summer hypolimnetic temp.") |
                         (season == "Summer air temp." & layer == "Summer epilimnetic temp."))) +
  facet_grid(rows = vars(layer), cols = vars(season))+
  stat_poly_eq(use_label(c("eq", "p")), coef.digits = 2) +
  xlab("Air temperature trend (ºC/y)") +
  ylab("Water temperature trend (ºC/y)") +
  theme_bw()
trend_seasons
dev.off()

density_water <- ALL %>%
  filter(source == "era5",
         layer %in% c("summer_epi_mean", "summer_hypo_mean")) %>%
  filter(!is.na(water_temp)) %>%
  ggplot(aes(y = water_temp)) +
  geom_hline(yintercept = 0, color = "grey75") +
  geom_density() +
  facet_grid(rows = vars(layer)) +
  theme_void() +
  theme(strip.text = element_blank())

density_air <- ALL %>%
  filter(source == "era5") %>%
  filter(!is.na(air_temp)) %>%
  ggplot(aes(x = air_temp)) +
  geom_vline(xintercept = 0, color = "grey75") +
  geom_density() +
  facet_grid(cols = vars(season)) +
  theme_void() +
  theme(strip.text = element_blank()) 

library(patchwork)
jpeg("temp_trend_seasons_density.jpg", width = 7, height = 7, units = "in", res = 300)
density_air + plot_spacer() + trend_seasons + density_water + 
  plot_layout(ncol = 2, nrow = 2, widths = c(5, 1), heights = c(1, 5))
dev.off()
library(ggpubr)
ggarrange(density_air, ggplot()+theme_void(), trend_seasons, density_water, 
          ncol = 2, nrow = 2, widths = c(4, 1), heights = c(1, 4), align = "hv")

with_temp <- read.csv("../Compiled data/All_data_annual.csv")

means <- with_temp %>%
  group_by(LakeID) %>%
  summarize(mean_Temp_C_HYPO = mean(Temp_C_HYPO, na.rm = T),
            mean_Temp_C_EPI = mean(Temp_C_EPI, na.rm = T),
            Summer = mean(temp_aug, na.rm = T),
            Spring = mean(temp_apr, na.rm = T)) %>%
  pivot_longer(cols = c("mean_Temp_C_EPI", "mean_Temp_C_HYPO"),
               names_to = "layer", values_to = "mean_water_temp") %>%
  pivot_longer(cols = c("Spring", "Summer"),
               names_to = "season", values_to = "mean_air_temp") %>%
  mutate(layer = ifelse(layer == "mean_Temp_C_EPI", "Epilimnion", "Hypolimnion"))

ALL %>%
  filter(source == "era5",
         layer %in% c("summer_epi_mean", "summer_hypo_mean")) %>%
  mutate(layer = ifelse(layer == "summer_epi_mean", "Epilimnion", "Hypolimnion")) %>%
  left_join(means) %>%
  mutate(water_temp = water_temp/mean_water_temp*100,
         air_temp = air_temp/mean_air_temp*100) %>%
  filter(!is.na(water_temp))%>%
  ggplot(aes(x = air_temp*10, y = water_temp*10)) +
  geom_hline(yintercept = 0, color = "grey75") +
  geom_vline(xintercept = 0, color = "grey75") +
  geom_abline(slope = 1, color = "black")+
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(rows = vars(layer), cols = vars(season), scales = "free")+
  stat_poly_eq(use_label(c("eq", "p")), coef.digits = 2) +
  xlab("Air temperature trend (%/decade)") +
  ylab("Water temperature trend (%/decade)") +
  theme_bw()

#Dug into the raw data here and this seems real
with_temp %>%
  filter(LakeID == "386") %>%
  ggplot(aes(x = Year, y = Temp_C_EPI)) +
  geom_point() 
```


Plot significant trends
```{r}
all_trends <- read.csv("hypo_temp_monthly.csv")

library(RColorBrewer)

all_trends %>%
  filter(!is.na(trend)) %>%
  group_by(Month) %>%
  summarize(n = n(),
            insig_pos = sum(trend > 0 & sig >= 0.05)/n,
            insig_neg = sum(trend < 0 & sig >= 0.05)/n,
            sig_pos = sum(trend > 0 & sig < 0.05)/n,
            sig_neg = sum(trend < 0 & sig < 0.05)/n) %>%
  pivot_longer(cols = c("insig_pos", "insig_neg", "sig_pos", "sig_neg")) %>%
  mutate(name = factor(name, 
                       levels = c("sig_neg","insig_neg","insig_pos","sig_pos"), 
                       labels = c("Significant cooling trend",
                                  "Insignificant trend",
                                  "Insignificant trend",
                                  "Significant warming trend"))) %>%
  ggplot(aes(x = Month, y = value, fill = name)) + 
  geom_bar(position="stack", stat="identity", color = "black") +
  scale_fill_manual(values = c("turquoise","grey90","lightcoral"), name = "") +
  geom_text(aes(y = 1.05, label = paste0("n = ", n))) + 
  theme_bw() +
  ylab("Proportion")

all_trends %>%
  filter(!is.na(trend)) %>%
  group_by(Month) %>%
  summarize(n = n(),
            n_sig = sum(sig < 0.05),
            sig_pos = sum(trend > 0 & sig < 0.05)/n_sig,
            sig_neg = sum(trend < 0 & sig < 0.05)/n_sig) %>%
  pivot_longer(cols = c("sig_pos", "sig_neg")) %>%
  mutate(name = factor(name, 
                       levels = c("sig_neg","sig_pos"), 
                       labels = c("Significant cooling trend",
                                  "Significant warming trend"))) %>%
  ggplot(aes(x = Month, y = value, fill = name)) + 
  geom_bar(position="stack", stat="identity", color = "black") +
  scale_fill_manual(values = c("turquoise","lightcoral"), name = "") +
  geom_text(aes(y = 1.05, label = paste0(n_sig, "/", n))) + 
  geom_text(aes(y = 0.75, label = paste0(round(value, 2)*100,"%")), 
            data = .%>%filter(name == "Significant cooling trend")) + 
  theme_bw() +
  ylab("Proportion\n(out of all lakes with significant trends)")
```

Plot ridges
```{r}
mean_sen <- read.csv("hypo_temp_mean_trends.csv")
summer_mean_sen <- read.csv("summer_hypo_temp_mean_trends.csv")
library(ggridges)

mean_trend <- mean(all_trends$trend, na.rm = T)
sd_trend <- sd(all_trends$trend, na.rm = T)

all_trends %>%
  ggplot(aes(x = trend, y = as.factor(Month))) + 
  geom_density_ridges(
    quantile_lines = TRUE,
    alpha = 1,
    point_alpha = 1,
    fill = "grey96",
    point_color = "grey30",
    point_fill = "white",
    #aes(point_fill = Var),
    point_shape = 21,
    scale=0.8) + 
  geom_vline(xintercept = 0) +
  coord_cartesian(xlim = c(mean_trend-sd_trend, mean_trend+sd_trend))

all_trends %>%
  ggplot(aes(y = trend, x = as.factor(Month)))+
  geom_boxplot()

neg <- all_trends %>%
  filter(!is.na(trend),
         trend < 0)

summary(lm(trend ~ Month, data = all_trends))
#install.packages("ordPens")
data_ord_aov <- all_trends %>%
  filter(!is.na(trend)) %>%
  mutate(Month = Month - 4)
ordPens::ordAOV(data_ord_aov$Month, data_ord_aov$trend)

with_mean <- all_trends %>%
  mutate(Month = as.character(Month)) %>%
  full_join(mean_sen %>%
              mutate(Month = "mean")) %>%
  full_join(summer_mean_sen %>%
              mutate(Month = "summer_mean"))

with_mean %>%
  filter(!is.na(trend)) %>%
  group_by(Month) %>%
  summarize(n = n(),
            insig_pos = sum(trend > 0 & sig >= 0.05)/n,
            insig_neg = sum(trend < 0 & sig >= 0.05)/n,
            sig_pos = sum(trend > 0 & sig < 0.05)/n,
            sig_neg = sum(trend < 0 & sig < 0.05)/n) %>%
  pivot_longer(cols = c("insig_pos", "insig_neg", "sig_pos", "sig_neg")) %>%
  mutate(name = factor(name, 
                       levels = c("sig_neg","insig_neg","insig_pos","sig_pos"), 
                       labels = c("Significant cooling trend",
                                  "Insignificant trend",
                                  "Insignificant trend",
                                  "Significant warming trend")),
         panel = ifelse(Month %in% c("mean", "summer_mean"), "mean", "numeric"),
         panel = factor(panel, levels = c("numeric","mean")),
         Month = factor(Month, 
                        levels = c("5", "6", "7", "8", "9", "mean", "summer_mean"),
                        labels = c("May", "Jun", "Jul", "Aug", "Sep", 
                                   "Strat. mean\ntemp", "Summer\ntemp"))) %>%
  ggplot(aes(x = Month, y = value, fill = name)) + 
  geom_bar(position="stack", stat="identity", color = "black") +
  scale_fill_manual(values = c("turquoise","grey90","lightcoral"), name = "") +
  geom_text(aes(y = 1.05, label = paste0("n = ", n))) + 
  theme_bw() +
  ylab("Proportion")+
  facet_grid(~panel, scales = "free_x", space = "free_x")+
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.title.x = element_blank())

with_mean %>%
  filter(!is.na(trend)) %>%
  group_by(Month) %>%
  summarize(n = n(),
            n_sig = sum(sig < 0.05),
            sig_pos = sum(trend > 0 & sig < 0.05)/n_sig,
            sig_neg = sum(trend < 0 & sig < 0.05)/n_sig) %>%
  pivot_longer(cols = c("sig_pos", "sig_neg")) %>%
  mutate(name = factor(name, 
                       levels = c("sig_neg","sig_pos"), 
                       labels = c("Significant cooling trend",
                                  "Significant warming trend")),
         panel = ifelse(Month %in% c("mean", "summer_mean"), "mean", "numeric"),
         panel = factor(panel, levels = c("numeric","mean")),
         Month = factor(Month, 
                        levels = c("5", "6", "7", "8", "9", "mean", "summer_mean"),
                        labels = c("May", "Jun", "Jul", "Aug", "Sep", 
                                   "Strat. mean\ntemp", "Summer\ntemp"))) %>%
  ggplot(aes(x = Month, y = value, fill = name)) + 
  geom_bar(position="stack", stat="identity", color = "black") +
  scale_fill_manual(values = c("turquoise","lightcoral"), name = "") +
  geom_text(aes(y = 1.05, label = paste0(n_sig, "/", n))) + 
  geom_text(aes(y = 0.75, label = paste0(round(value, 2)*100,"%")), 
            data = .%>%filter(name == "Significant cooling trend")) + 
  theme_bw() +
  ylab("Proportion\n(out of all lakes with significant trends)")+
  facet_grid(~panel, scales = "free_x", space = "free_x")+
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.title.x = element_blank())
```


```{r}
warming <- read.csv("warming_sen.csv")

mean_sen %>%
  rename(trend_mean = trend, sig_mean = sig) %>%
  select(LakeID, trend_mean, sig_mean) %>%
  left_join(warming) %>%
  filter(!is.na(trend) & !is.na(sig) & sig < 0.05) %>%
  ggplot(aes(x = trend_mean, fill = trend < 0)) +
  geom_density(alpha = 0.5)

mean_sen %>%
  rename(trend_mean = trend, sig_mean = sig) %>%
  select(LakeID, trend_mean, sig_mean) %>%
  left_join(warming) %>%
  filter(trend > 0)

mean_sen %>%
  rename(trend_mean = trend, sig_mean = sig) %>%
  select(LakeID, trend_mean, sig_mean) %>%
  left_join(warming) %>%
  filter(!is.na(trend)) %>%
  ggplot(aes(x = trend_mean, fill = trend < 0)) +
  geom_density(alpha = 0.5)

mean_sen %>%
  rename(trend_mean = trend, sig_mean = sig) %>%
  select(LakeID, trend_mean, sig_mean) %>%
  left_join(warming) %>%
  filter(!is.na(trend)) %>%
  ggplot(aes(x = trend_mean, y = trend)) +
  geom_point()

summer_mean_sen %>%
  filter(sig < 0.05) %>%
  rename(trend_mean = trend, sig_mean = sig) %>%
  select(LakeID, trend_mean, sig_mean) %>%
  left_join(warming) %>%
  filter(!is.na(trend)) %>%
  ggplot(aes(y = trend_mean, x = trend)) +
  geom_smooth(method = "lm")+
  geom_point(aes(color = sig < 0.05))

jpeg("../Figures/warming_rate_trends.jpg", res = 300, width = 3, height = 3, units = "in")
warming %>%
  filter(!is.na(trend)) %>%
  ggplot(aes(x = trend <0, fill = sig < 0.05))+
  geom_bar() +
  ylab("Warming rate trend")+
  scale_x_discrete(breaks = c(T, F), labels = c("Decrease", "Increase")) +
  theme_bw()+
  theme(axis.title.x = element_blank())
dev.off()
```

Hypo temp
```{r}
library(ggthemes)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
#remotes::install_github("ropensci/rnaturalearthhires")
library(rnaturalearthhires)
library(ggspatial)
library(viridis)
library(ggpubr)

lat_long = read.csv("https://pasta-s.lternet.edu/package/data/eml/edi/1029/9/fadd3eaa25b5fdd1fc4efba70e660579")
summer_mean_sen <- read.csv("summer_hypo_temp_mean_trends.csv")

all_trends <- summer_mean_sen %>%
  filter(!is.na(trend))
min = min(all_trends$trend)*10
max = max(all_trends$trend)*10
abs_max = max(abs(c(min,max)))

states <- ne_states(returnclass = "sf", country = "United States of America")
world <- ne_countries(scale = "medium", returnclass = "sf")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(25, 50), xlim = c(-130,-60)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Hypo. temp. trend\n(ºC/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/hypo_temp_map_us.jpeg", width = 8, height = 3.5, units = "in", res = 300)
us_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Hypo. temp. trend\n(ºC/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/hypo_temp_map_wi.jpeg", width = 3, height = 3.5, units = "in", res = 300)
us_map
dev.off()

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-76,-67)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Hypo. temp. trend\n(ºC/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/hypo_temp_map_ne.jpeg", width = 4, height = 3.5, units = "in", res = 300)
us_map
dev.off()

for_euro <- all_trends %>%
  left_join(lat_long)

euro_map = ggplot(data = world) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(43, 70), xlim = c(-5,30)) +
  geom_point(data = for_euro, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Hypo. temp. trend\n(ºC/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/hypo_temp_map_euro.jpeg", width = 3, height = 3.5, units = "in", res = 300)
euro_map
dev.off()

#clustering
library(ncf)
library(pgirmess)
for_cor_ne <- all_trends %>%
  left_join(lat_long) %>%
  rename(Y = Latitude_DD,
         X = Longitude_DD) %>%
  filter(X >= -76, 
         X <= -67,
         Y >= 42,
         Y <= 47.5)

pgi.cor.ne <- pgirmess::correlog(coords=as.matrix(for_cor_ne[c("X","Y")]), 
                              z=for_cor_ne[["trend"]], method="Moran")
ncf.cor.spline.ne <- ncf::spline.correlog(for_cor_ne$X, for_cor_ne$Y, 
                                       for_cor_ne$trend, latlon = T, resamp=500)

for_cor_wi <- all_trends %>%
  left_join(lat_long) %>%
  rename(Y = Latitude_DD,
         X = Longitude_DD) %>%
  filter(X >= -93, 
         X <= -86.5,
         Y >= 42,
         Y <= 47.5)

pgi.cor.wi <- pgirmess::correlog(coords=as.matrix(for_cor_wi[c("X","Y")]), 
                              z=for_cor_wi[["trend"]], method="Moran")
ncf.cor.spline.wi <- ncf::spline.correlog(for_cor_wi$X, for_cor_wi$Y, 
                                       for_cor_wi$trend, latlon = T, resamp=500)
plot(ncf.cor.spline.wi)
plot(ncf.cor.spline.ne)
plot(pgi.cor.wi)
plot(pgi.cor.ne)

library(gstat)
var_results_wi <- variogram(trend~1, data = for_cor_wi, locations = ~X+Y)
plot(var_results_wi)
var_results_ne <- variogram(trend~1, data = for_cor_ne, locations = ~X+Y)
plot(var_results_ne)
```

Warming rate
```{r}
warming <- read.csv("warming_sen.csv")
all_trends <- warming %>%
  filter(!is.na(trend))
min = min(all_trends$trend)*10
max = max(all_trends$trend)*10
abs_max = max(abs(c(min,max)))

states <- ne_states(returnclass = "sf", country = "United States of America")
world <- ne_countries(scale = "medium", returnclass = "sf")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(25, 50), xlim = c(-130,-60)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Warming rate trend\n(ºC/d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_us.jpeg", width = 8, height = 3.5, units = "in", res = 300)
us_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Warming rate trend\n(ºC/d/decade)",
                       colours = c("blue","blue","white","red","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_wi.jpeg", width = 3, height = 3.5, units = "in", res = 300)
us_map
dev.off()

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-76,-67)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Warming rate trend\n(ºC/d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_ne.jpeg", width = 4, height = 3.5, units = "in", res = 300)
us_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_euro <- all_trends %>%
  left_join(lat_long)

euro_map = ggplot(data = world) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(43, 70), xlim = c(-5,30)) +
  geom_point(data = for_euro, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "Warming rate trend\n(ºC/d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_euro.jpeg", width = 3, height = 3.5, units = "in", res = 300)
euro_map
dev.off()


#clustering
library(ncf)
library(pgirmess)
for_cor_ne <- all_trends %>%
  left_join(lat_long) %>%
  rename(Y = Latitude_DD,
         X = Longitude_DD) %>%
  filter(X >= -76, 
         X <= -67,
         Y >= 42,
         Y <= 47.5)

pgi.cor.ne <- pgirmess::correlog(coords=as.matrix(for_cor_ne[c("X","Y")]), 
                              z=for_cor_ne[["trend"]], method="Moran")
ncf.cor.spline.ne <- ncf::spline.correlog(for_cor_ne$X, for_cor_ne$Y, 
                                       for_cor_ne$trend, latlon = T, resamp=500)

for_cor_wi <- all_trends %>%
  left_join(lat_long) %>%
  rename(Y = Latitude_DD,
         X = Longitude_DD) %>%
  filter(X >= -93, 
         X <= -86.5,
         Y >= 42,
         Y <= 47.5)

pgi.cor.wi <- pgirmess::correlog(coords=as.matrix(for_cor_wi[c("X","Y")]), 
                              z=for_cor_wi[["trend"]], method="Moran")
ncf.cor.spline.wi <- ncf::spline.correlog(for_cor_wi$X, for_cor_wi$Y, 
                                       for_cor_wi$trend, latlon = T, resamp=500)
plot(ncf.cor.spline.wi)
plot(ncf.cor.spline.ne)
plot(pgi.cor.wi)
plot(pgi.cor.ne)

library(gstat)
var_results_wi <- variogram(trend~1, data = for_cor_wi, locations = ~X+Y)
plot(var_results_wi)
var_results_ne <- variogram(trend~1, data = for_cor_ne, locations = ~X+Y)
plot(var_results_ne)
```

Warming rate discrete
```{r}
all_trends <- warming %>%
  filter(!is.na(trend))
min = min(all_trends$trend)*10
max = max(all_trends$trend)*10
abs_max = max(abs(c(min,max)))

states <- ne_states(returnclass = "sf", country = "United States of America")
world <- ne_countries(scale = "medium", returnclass = "sf")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA",
         !is.na(trend)) %>%
  mutate(class = ifelse(trend<0 & sig < 0.05,
                        "decrease",
                        ifelse(trend > 0 & sig < 0.05,
                               "increase",
                               "no sig change")))

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(25, 50), xlim = c(-130,-60)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = class),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_manual(name = "Warming rate trend",
                    values = c("blue","white","red"),
                    breaks = c("decrease","no sig change", "increase"))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_us.jpeg", width = 8, height = 3.5, units = "in", res = 300)
us_map
dev.off()

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = class),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_manual(name = "Warming rate trend",
                    values = c("blue","white","red"),
                    breaks = c("decrease","no sig change", "increase"))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_wi.jpeg", width = 3, height = 3.5, units = "in", res = 300)
us_map
dev.off()

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-76,-67)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = class),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_manual(name = "Warming rate trend",
                    values = c("blue","white","red"),
                    breaks = c("decrease","no sig change", "increase"))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_ne.jpeg", width = 4, height = 3.5, units = "in", res = 300)
us_map
dev.off()

for_euro <- all_trends %>%
  left_join(lat_long) %>%
  mutate(class = ifelse(trend<0 & sig < 0.05,
                        "decrease",
                        ifelse(trend > 0 & sig < 0.05,
                               "increase",
                               "no sig change")))

euro_map = ggplot(data = world) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(43, 70), xlim = c(-5,30)) +
  geom_point(data = for_euro, 
             aes(Longitude_DD, Latitude_DD, fill = class),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_manual(name = "Warming rate trend",
                    values = c("blue","white","red"),
                    breaks = c("decrease","no sig change", "increase"))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/warming_rate_map_euro.jpeg", width = 3, height = 3.5, units = "in", res = 300)
euro_map
dev.off()
```


DO
```{r}
summer_do_trends <- read.csv("summer_do_trends.csv")

all_trends <- summer_do_trends %>%
  filter(!is.na(trend))
min = min(all_trends$trend)*10
max = max(all_trends$trend)*10
abs_max = max(abs(c(min,max)))

states <- ne_states(returnclass = "sf", country = "United States of America")
world <- ne_countries(scale = "medium", returnclass = "sf")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(25, 50), xlim = c(-130,-60)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "DO trend\n(mg/L/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/do_map_us.jpeg", width = 8, height = 3.5, units = "in", res = 300)
us_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "DO trend\n(mg/L/decade)",
                       colours = c("blue","blue","white","red","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/do_map_wi.jpeg", width = 3, height = 3.5, units = "in", res = 300)
us_map
dev.off()

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-76,-67)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "DO trend\n(mg/L/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/do_map_ne.jpeg", width = 4, height = 3.5, units = "in", res = 300)
us_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_euro <- all_trends %>%
  left_join(lat_long)

euro_map = ggplot(data = world) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(43, 70), xlim = c(-5,30)) +
  geom_point(data = for_euro, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "DO trend\n(mg/L/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/do_map_euro.jpeg", width = 3, height = 3.5, units = "in", res = 300)
euro_map
dev.off()
```

AF
```{r}
summer_af_trends <- read.csv("summer_af_trends.csv")

all_trends <- summer_af_trends %>%
  filter(!is.na(trend))
min = min(all_trends$trend)*10
max = max(all_trends$trend)*10
abs_max = max(abs(c(min,max)))

states <- ne_states(returnclass = "sf", country = "United States of America")
world <- ne_countries(scale = "medium", returnclass = "sf")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(25, 50), xlim = c(-130,-60)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "AF trend\n(d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/af_map_us.jpeg", width = 8, height = 3.5, units = "in", res = 300)
us_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

wi_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "AF trend\n(d/decade)",
                       colours = c("blue","blue","white","red","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/af_map_wi.jpeg", width = 3, height = 3.5, units = "in", res = 300)
wi_map
dev.off()

ne_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-76,-67)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "AF trend\n(d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/af_map_ne.jpeg", width = 4, height = 3.5, units = "in", res = 300)
ne_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_euro <- all_trends %>%
  left_join(lat_long)

euro_map = ggplot(data = world) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(43, 70), xlim = c(-5,30)) +
  geom_point(data = for_euro, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "AF trend\n(d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/af_map_euro.jpeg", width = 3, height = 3.5, units = "in", res = 300)
euro_map
dev.off()

ggarrange(euro_map, ne_map, wi_map, nrow = 1, align = "hv")
```

VHOD
```{r}
summer_vhod_trends <- read.csv("summer_vhod_trends.csv")

all_trends <- summer_vhod_trends %>%
  filter(!is.na(trend))
min = min(all_trends$trend)*10
max = max(all_trends$trend)*10
abs_max = max(abs(c(min,max)))

states <- ne_states(returnclass = "sf", country = "United States of America")
world <- ne_countries(scale = "medium", returnclass = "sf")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

us_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(25, 50), xlim = c(-130,-60)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "VHOD trend\n(d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/vhod_map_us.jpeg", width = 8, height = 3.5, units = "in", res = 300)
us_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_states <- all_trends %>%
  left_join(lat_long) %>%
  filter(Country == "USA")

wi_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "VHOD trend\n(d/decade)",
                       colours = c("blue","blue","white","red","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/vhod_map_wi.jpeg", width = 3, height = 3.5, units = "in", res = 300)
wi_map
dev.off()

ne_map = ggplot(data = states) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-76,-67)) +
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "VHOD trend\n(d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/vhod_map_ne.jpeg", width = 4, height = 3.5, units = "in", res = 300)
ne_map
dev.off()

states <- ne_states(returnclass = "sf", country = "United States of America")

for_euro <- all_trends %>%
  left_join(lat_long)

euro_map = ggplot(data = world) +
  geom_sf(fill = "grey90", color = "grey60") +
  coord_sf(expand = FALSE, ylim = c(43, 70), xlim = c(-5,30)) +
  geom_point(data = for_euro, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey30", size = 2, alpha  =.7, stroke = .4)+
  theme_bw()+
  scale_fill_gradientn(name = "VHOD trend\n(d/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "white"),
        legend.position = "bottom")
jpeg("../Figures/vhod_map_euro.jpeg", width = 3, height = 3.5, units = "in", res = 300)
euro_map
dev.off()

ggarrange(euro_map, ne_map, wi_map, nrow = 1, align = "hv")
```