---
title: "Temp trend maps"
author: "Abby Lewis"
date: "2023-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(trend) #switched from open air 7 Nov 2023

# Make a directory for Figures if there isn't one
if (!dir.exists("../Figures")){dir.create("../Figs")}
```

```{r}
lat_long = read.csv("https://pasta-s.lternet.edu/package/data/eml/edi/1029/9/fadd3eaa25b5fdd1fc4efba70e660579")

climate_narr = read.csv("../Compiled data/historical_temp_output_narr.csv")
climate_jra55 = read.csv("../Compiled data/historical_temp_output_jra55.csv")
climate_era5 = read.csv("../Compiled data/historical_temp_output_era5.csv")
```

```{r}
sen_slope_climate <- function(df,var){
  df <- df %>%
    mutate(date = ymd_hms(paste(Year,"-01-01 00:00:00")))
  output = df %>%
    group_by(LakeID)%>%
    dplyr::summarize(n = n(),
                     trend = NA,
                     sig = NA,
                     min_year = NA,
                     max_year = NA)
  for(lake in unique(df$LakeID)){
      filt = df%>%
        filter(LakeID==lake)
      if(length(unique(filt$Year))>=5){
        sen = trend::sens.slope(filt[[var]])
        output$trend[output$LakeID==lake]<-sen$estimates[1]
        output$sig[output$LakeID==lake]<-sen$p.value[1]
        output$min_year[output$LakeID==lake]<-min(year(filt$date))
        output$max_year[output$LakeID==lake]<-max(year(filt$date))
      }
  }
  return(output)
}

sen_slope_months <- function(df, var, months = 1:12) {
  output <- sen_slope_climate(df%>%filter(Month == months[1]), var)%>%
    mutate(Month = months[1])
  
  if(length(months)>1){
    for (month in months[2:length(months)]) {
      output <- rbind(output, 
                      sen_slope_climate(df%>%filter(Month == month), var)%>%
                        mutate(Month = month)
    )
    }
  }
  
  # Save output only if all months were run
  if(length(months)==12){
    write.csv(output, paste0("../Compiled data/", 
                             deparse(substitute(df)), "_",
                             deparse(substitute(var)), ".csv"), 
              row.names = F)
  }
  
  return(output)
}

climate_narr_trends <- sen_slope_months(climate_narr %>% filter(Year > 1980), 
                                        "Temp_C") #takes ~10 seconds
climate_jra55_trends <- sen_slope_months(climate_jra55 %>% filter(Year > 1980), 
                                         "Temp_C")
climate_era5_trends <- sen_slope_months(climate_era5 %>% filter(Year > 1980), 
                                        "Temp_C")
```

Lots of code here that could be deleted since I switched to facets
```{r}
library(ggthemes)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
#remotes::install_github("ropensci/rnaturalearthhires")
library(rnaturalearthhires)
library(ggspatial)
library(viridis)
library(ggpubr)

# Function to plot a map of a given month with a given dataset
plot_wi_trend_monthly <- function(temp_trends,
                                  month,
                                  min = NULL,
                                  max = NULL) {
  
  if(is.null(min)) {min = min(temp_trends$trend)*10} else {min = min*10} #per decade
  if(is.null(max)) {max = max(temp_trends$trend)*10} else {max = max*10}
  
  for_states <- temp_trends%>%
    filter(Month==month)%>%
    left_join(lat_long)
  states <- ne_states(returnclass = "sf",country = "United States of America")
  
  us_map = ggplot(data = states) +
    geom_sf() +
    coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5))+
    geom_point(data = for_states, 
               aes(Longitude_DD, Latitude_DD, fill = trend*10),
               shape = 21, color = "white", size = 2.8, alpha  =.5, stroke = .4)+
    theme_bw()+
    theme(plot.margin = margin(0, 0, 0, 0, "cm"),
      legend.box.background = element_rect(fill = "white", color = "white"))+
    scale_fill_viridis(name = "Air temperature trend\n(ºC/decade)",
                       limits = c(min,max), option = "H")+
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank())+
    ggtitle(paste0(month.name[month]))
  us_map
}

plot_wi_trend_multimonth <- function(temp_trends, months = NULL, min = NULL, max = NULL) {
  if(is.null(months)){months <- unique(temp_trends$Month)}
  if(is.null(min)) {min = min(temp_trends$trend, na.rm = T)}
  if(is.null(max)) {max = max(temp_trends$trend, na.rm = T)}
  n_months <- length(unique(months))
  plot_list <- vector(mode='list', length=n_months)
  for(i in 1:n_months) {
    plot <- plot_wi_trend_monthly(temp_trends,
                                  months[i],
                                  min = min,
                                  max = max)
    plot_list[[i]] <- plot
  }
  return(plot_list)
}

plot_wi_trend_multimodel <- function(temp_trends1, 
                                     temp_trends2,
                                     temp_trends3 = NULL) {
  
  full <- rbind(temp_trends1, temp_trends2, temp_trends3)
  if(is.null(months)){months <- unique(full$Month)}
  min <- min(full$trend, na.rm = T)
  max <- max(full$trend, na.rm = T)
  n_models <- ifelse(is.null(temp_trends3), 2, 3)
  plot_list <- vector(mode='list', length=n_models*length(months))
  plot_list[1:length(months)] <- plot_wi_trend_multimonth(temp_trends1, 
                                                          months = months,
                                                          min = min,
                                                          max = max)
  plot_list[(length(months)+1):(2*length(months))] <- plot_wi_trend_multimonth(temp_trends2, 
                                                          months = months,
                                                          min = min,
                                                          max = max)
  if(!is.null(temp_trends3)){
    plot_list[(2*length(months)+1):(3*length(months))] <- plot_wi_trend_multimonth(temp_trends3, 
                                                          months = months,
                                                          min = min,
                                                          max = max)
  }
  do.call(ggarrange, c(plot_list[1:length(plot_list)], 
                       ncol = length(months), 
                       nrow = n_models,
                       common.legend = T))
}

plot_wi_trend_multimodel(climate_narr_trends, 
                         climate_era5_trends, 
                         climate_jra55_trends)
```

Probably way easier to do this with facets
```{r}
library(ggthemes)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
#remotes::install_github("ropensci/rnaturalearthhires")
library(rnaturalearthhires)
library(ggspatial)
library(viridis)
library(ggpubr)

all_trends <- climate_narr_trends%>%
  mutate(Model = "NARR") %>%
  full_join(climate_era5_trends %>% mutate(Model = "ERA5")) %>%
  full_join(climate_jra55_trends %>% mutate(Model = "JRA55")) %>%
  mutate(Month = factor(Month, 
                        levels = unique(Month), 
                        labels = month.abb[unique(Month)],
                        ordered = T))
min = min(all_trends$trend)*10
max = max(all_trends$trend)*10
abs_max = max(abs(c(min,max)))

for_states <- all_trends%>%
  left_join(lat_long)
states <- ne_states(returnclass = "sf",country = "United States of America")

us_map = ggplot(data = states) +
  geom_sf(fill = "white") +
  coord_sf(expand = FALSE, ylim = c(42, 47.5), xlim = c(-93,-86.5))+
  geom_point(data = for_states, 
             aes(Longitude_DD, Latitude_DD, fill = trend*10),
             shape = 21, color = "grey50", size = 2, alpha  =.5, stroke = .4)+
  theme_bw()+
  #scale_fill_viridis(name = "Air temperature trend\n(ºC/decade)",
  #                   limits = c(min,max), option = "H")+
  scale_fill_gradientn(name = "Air temperature trend\n(ºC/decade)",
                       colours = c("blue","white","red"),
                       limits = c(-abs_max, abs_max))+
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.background = element_rect(fill = "grey80"),
        legend.position = "bottom")+
  facet_grid(rows = vars(Model), cols = vars(Month))
jpeg("../Figures/temperature_trends.jpeg", width = 8, height = 3.5, units = "in", res = 300)
us_map
dev.off()

us_map

hists = all_trends%>%
  mutate(trend = trend*10)%>%
  ggplot(aes(x = trend, fill = Model))+
  geom_density(alpha = 1, linewidth = 0.1)+
  theme_bw()+
  coord_cartesian(ylim=c(0, 10))+
  scale_x_continuous(breaks = c(-0.8,0,0.8), name = "Air temperature trend (ºC/decade)")+
  geom_vline(xintercept = 0)+
  scale_fill_viridis_d()+
  facet_grid(cols = vars(Month))

library(patchwork)
jpeg("../Figures/temperature_trends_hist.jpeg", width = 10, height = 5, units = "in", res = 300)
wrap_plots(us_map+theme(legend.position = "right"), hists, ncol = 1, heights = c(2,1))
dev.off()

hists2 = all_trends%>%
  mutate(trend = trend*10)%>%
  ggplot(aes(x = trend, fill = Model))+
  geom_density()+
  theme_bw()+
  scale_x_continuous(breaks = c(-0.9,0,0.9), name = "Air temperature trend (ºC/decade)")+
  geom_vline(xintercept = 0)+
  scale_fill_viridis_d()+
  facet_wrap(~Month)

jpeg("../Figures/temperature_trends_hist_only.jpeg", width = 6, height = 5, units = "in", res = 300)
hists2
dev.off()


hists3 = all_trends%>%
  mutate(trend = trend*10)%>%
  ggplot(aes(x = trend, fill = Model))+
  geom_density()+
  theme_bw()+
  scale_x_continuous(breaks = c(-0.9,0,0.9), name = "Air temperature trend (ºC/decade)")+
  geom_vline(xintercept = 0)+
  scale_fill_viridis_d()+
  facet_grid(cols = vars(Month), rows = vars(Model), scales = "free_y")

jpeg("../Figures/temperature_trends_hist_all.jpeg", width = 10, height = 5, units = "in", res = 300)
wrap_plots(us_map+theme(legend.position = "right"), hists3, ncol = 1)
dev.off()
```

