---
title: "JRA-55"
author: "Abby Lewis"
date: "2023-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(TZ='UTC')
library(ncdf4)
library(ggplot2)
library(fields)
library(tidyverse)
library(data.table)
library(lubridate)
```

```{r}
#Read and format our lake metadata
lakes <- read.csv("https://pasta-s.lternet.edu/package/data/eml/edi/1029/9/fadd3eaa25b5fdd1fc4efba70e660579") 
lakes_format <- lakes %>%
  filter(StateOrProvince == "Wisconsin")%>%
  dplyr::select(LakeID,Longitude_DD,Latitude_DD) %>%
  rename(Lon=Longitude_DD,Lat=Latitude_DD)%>%
  filter(!is.na(Lon),
         !is.na(Lat))


#Read NC temp
folder <- '../External data/JRA-55'
files <- list.files(folder)
output <- data.frame(LakeID = character(),
                     Month = numeric(),
                     Year = numeric(),
                     Temp_C = numeric(),
                     Lon = numeric(),
                     Lat = numeric())
for (file in files) {
  mynetcdf_t <- paste0('../External data/JRA-55/',file)
  ncFile_t <- nc_open(mynetcdf_t)
  Lon <- ncvar_get(ncFile_t,"g4_lon_2")
  Lon <- ifelse(Lon > 180, -(360 - Lon), Lon)
  Lat <- ncvar_get(ncFile_t,"g4_lat_1")
  time <- ncvar_get(ncFile_t,"initial_time0_hours")
  t_mean <- ncvar_get(ncFile_t,"TMP_GDS4_HTGL_S123")
  fillvalue <- ncatt_get(ncFile_t, "TMP_GDS4_HTGL_S123","missing_value") 
  t_mean[t_mean == fillvalue$value] <- NA
  months <- month(as.Date("1800-01-01")+hours(time))
  years <- year(as.Date("1800-01-01")+hours(time))
  
  #Loop through lakes and add temp data based on lat/lon
  combined_t_df <- data.frame(LakeID = rep(lakes_format$LakeID, each = length(months)),
                             Month = rep(months,nrow(lakes_format)),
                             Year = rep(years,nrow(lakes_format)),
                             Temp_C = as.numeric(NA),
                             Lon = as.numeric(NA),
                             Lat = as.numeric(NA)
                             )
  for(i in 1:nrow(lakes_format)){
    lon_id <- ifelse(min(abs(lakes_format[i,]$Lon-Lon))<=0.5,which.min(abs(lakes_format[i,]$Lon-Lon)),NA)
    lat_id <- ifelse(min(abs(lakes_format[i,]$Lat-Lat))<=0.5, which.min(abs(lakes_format[i,]$Lat-Lat)),NA)
    if(!is.na(lon_id)&!is.na(lat_id)){
      t_vector <- t_mean[lon_id, lat_id, 1:length(time)] 
      combined_t_df$Temp_C[combined_t_df$LakeID==lakes_format[i,]$LakeID]<- t_vector-273.15
      combined_t_df$Lon[combined_t_df$LakeID==lakes_format[i,]$LakeID]<- Lon[lon_id]
      combined_t_df$Lat[combined_t_df$LakeID==lakes_format[i,]$LakeID]<- Lat[lat_id]
    }
  }
  combined_t_df <- combined_t_df%>%
    mutate(Temp_C = trunc(Temp_C*100000)/100000)
  
  output <- rbind(output,combined_t_df)
}
write.csv(output,"../Compiled data/historical_temp_output_jra55.csv", row.names = F)
```

